/**
 * `otpauth://totp/…` URIs — the de facto interchange format for TOTP pairing
 * (Google Authenticator's "Key URI Format"), used by effectively every
 * service and every authenticator app even though it is not itself an RFC.
 * RFC 6238 defines the algorithm; this format is how a secret and its
 * parameters travel as one string, in a QR or on the clipboard.
 *
 * `otpauth://totp/<label>?secret=<base32>&issuer=<name>&algorithm=<SHA1|SHA256|SHA512>&digits=<6-8>&period=<seconds>`
 *
 * `<label>` is `issuer:account` (colon-separated) or just `account`. The
 * `issuer` query parameter is the authoritative one when both are present and
 * disagree — that is the documented behaviour of every mainstream
 * authenticator, kept here so a URI generated by this app round-trips through
 * a real phone authenticator and back.
 */

import { base32Decode, base32Encode, isValidBase32 } from "./base32";
import { DEFAULT_ALGORITHM, DEFAULT_DIGITS, DEFAULT_PERIOD, MAX_DIGITS, MIN_DIGITS, TOTP_ALGORITHMS, type TotpAlgorithm } from "./totp";

export interface OtpauthParams {
  issuer: string;
  account: string;
  /** Base32-encoded secret, as it appears in the URI (no spaces). */
  secret: string;
  algorithm: TotpAlgorithm;
  digits: number;
  period: number;
}

export class OtpauthUriError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OtpauthUriError";
  }
}

function normalizeAlgorithm(raw: string | null): TotpAlgorithm {
  if (!raw) return DEFAULT_ALGORITHM;
  const upper = raw.toUpperCase();
  const match = TOTP_ALGORITHMS.find(a => a === upper);
  if (!match) throw new OtpauthUriError(`unsupported algorithm: ${raw} (expected SHA1, SHA256, or SHA512)`);
  return match;
}

function normalizeDigits(raw: string | null): number {
  if (!raw) return DEFAULT_DIGITS;
  const n = Number(raw);
  if (!Number.isInteger(n) || n < MIN_DIGITS || n > MAX_DIGITS) {
    throw new OtpauthUriError(`digits must be an integer ${MIN_DIGITS}-${MAX_DIGITS}, got ${raw}`);
  }
  return n;
}

function normalizePeriod(raw: string | null): number {
  if (!raw) return DEFAULT_PERIOD;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0) throw new OtpauthUriError(`period must be a positive number of seconds, got ${raw}`);
  return n;
}

/**
 * Build an `otpauth://` URI from validated fields. Throws rather than
 * emitting a URI a scanner would misread — a truncated or malformed payload
 * that "looks like a QR" is worse than no QR (see `gui/src/lib/qr.ts`).
 */
export function buildOtpauthUri(params: OtpauthParams): string {
  if (!isValidBase32(params.secret)) throw new OtpauthUriError("secret is not valid base32");
  if (!params.account.trim()) throw new OtpauthUriError("account is required");
  const label = params.issuer.trim() ? `${params.issuer.trim()}:${params.account.trim()}` : params.account.trim();
  const search = new URLSearchParams();
  search.set("secret", params.secret.replace(/[\s-]/g, "").replace(/=+$/, "").toUpperCase());
  if (params.issuer.trim()) search.set("issuer", params.issuer.trim());
  search.set("algorithm", params.algorithm);
  search.set("digits", String(params.digits));
  search.set("period", String(params.period));
  // encodeURIComponent, not URL's own path encoding, so a `:` in the label
  // (the issuer/account separator) survives — URL would otherwise leave it
  // un-encoded in a way some scanners split on differently.
  return `otpauth://totp/${encodeURIComponent(label)}?${search.toString()}`;
}

/** Parse an `otpauth://totp/…` URI. Throws `OtpauthUriError` for anything malformed or unsupported. */
export function parseOtpauthUri(uri: string): OtpauthParams {
  let url: URL;
  try {
    url = new URL(uri.trim());
  } catch {
    throw new OtpauthUriError("not a valid URI");
  }
  if (url.protocol !== "otpauth:") throw new OtpauthUriError(`expected an otpauth:// URI, got ${url.protocol}//`);
  const type = url.hostname.toLowerCase();
  if (type === "hotp") throw new OtpauthUriError("HOTP (counter-based) pairing is not supported — this authenticator is TOTP-only");
  if (type !== "totp") throw new OtpauthUriError(`unsupported otpauth type: ${type} (expected totp)`);

  const label = decodeURIComponent(url.pathname.replace(/^\//, ""));
  if (!label) throw new OtpauthUriError("missing label (issuer:account)");
  const colonIndex = label.indexOf(":");
  const labelIssuer = colonIndex >= 0 ? label.slice(0, colonIndex).trim() : "";
  const labelAccount = colonIndex >= 0 ? label.slice(colonIndex + 1).trim() : label.trim();
  if (!labelAccount) throw new OtpauthUriError("missing account in label");

  const secretRaw = url.searchParams.get("secret");
  if (!secretRaw) throw new OtpauthUriError("missing secret parameter");
  if (!isValidBase32(secretRaw)) throw new OtpauthUriError("secret is not valid base32");

  // The query `issuer` parameter is authoritative when present and disagrees
  // with the label — this is the documented, widely-implemented convention.
  const queryIssuer = url.searchParams.get("issuer");
  const issuer = (queryIssuer ?? labelIssuer).trim();

  return {
    issuer,
    account: labelAccount,
    secret: secretRaw.replace(/[\s-]/g, "").replace(/=+$/, "").toUpperCase(),
    algorithm: normalizeAlgorithm(url.searchParams.get("algorithm")),
    digits: normalizeDigits(url.searchParams.get("digits")),
    period: normalizePeriod(url.searchParams.get("period")),
  };
}

/** Re-encode a base32 secret string as raw bytes, for handing to `totp()`/`hotp()`. */
export function secretBytes(base32Secret: string): Uint8Array {
  return base32Decode(base32Secret);
}

/** Raw bytes back to the canonical (unpadded, uppercase) base32 string used in URIs and storage. */
export function encodeSecret(bytes: Uint8Array): string {
  return base32Encode(bytes, { padding: false });
}
