/**
 * Release line-count attribution arithmetic.
 *
 * This used to call `countLines()` and `countLinesWithAttribution()` at module top level,
 * scanning this project's own ~4,900 tracked files before any test body ran. That work sat
 * outside every per-test timeout — `scripts/test.ts` only bounds individual tests, not module
 * import — and `countLines()`'s per-file `git show` calls used to run one at a time, so the
 * import alone could cost minutes. That is the defect tests/hunt-rel-02.test.ts pins directly;
 * the fix here is architectural: build a small synthetic git repository with known content in a
 * temp directory inside `beforeAll` (still outside a `test()` body, but now cheap — a handful of
 * files and two commits, not a few thousand), and assert exact expected numbers against it
 * instead of merely checking the shape of whatever the real repository happens to contain.
 *
 * The exact numbers are not a fact about this project's own source (those still are not pinned,
 * and still should not be — every surviving source edit would change them). They are facts about
 * the fixture this file builds, so every expected total below is derived from the same literal
 * line arrays used to write the fixture files, not hand-counted.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { countLines } from "../scripts/count-lines";
import {
  EXCLUDED_AGENT_LOOKALIKES,
  KNOWN_AGENT_IDENTITIES,
  countLinesWithAttribution,
  formatLineAttributionTable,
  isAgentAttribution,
} from "../scripts/line-attribution";

function git(root: string, args: string[]): void {
  const result = spawnSync("git", args, { cwd: root, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`git ${args.join(" ")} failed (exit ${String(result.status)}): ${result.stderr || result.stdout}`);
  }
}

/** One fixture file's content, as an explicit array of lines rather than a hand-joined string, so the expected `total`/`code` below are computed from the same array instead of counted by eye. */
const FIXTURE_FILES: Record<string, readonly string[]> = {
  // Matches the "Generated (icons, catalogues)" bucket's exact-path rule.
  "gui/src/icons.tsx": ["// generated by scripts/gen-icons.ts", "export const icons = {};"],
  // Matches "Tests": both the `tests?/` path rule and the `.test.ts` suffix rule.
  "tests/example.test.ts": ["test('x', () => {});"],
  // Matches "Desktop shell (Electron)".
  "electron/main.ts": ["console.log('electron');"],
  // Matches "Dashboard — source" (gui/ but not .css, not icons.tsx).
  "gui/src/App.tsx": ["export function App() {", "  return null;", "}"],
  // Matches "Docs & prose (Markdown)".
  "README.md": ["# fixture", "", "One known line."],
  // Matches "Config & manifests", the catch-all — nothing above it matches this path.
  "config.json": ["{", "  \"a\": 1", "}"],
};

/** Code-extension files whose bytes are deliberately unreadable, so `unreadable` is exercised and pinned rather than left to whatever the real repository happens to contain. */
const UNREADABLE_FILES: Record<string, Buffer> = {
  // Invalid UTF-8 (a lone 0xFF byte is never valid): fails the `utf8.decode()` step.
  "src/invalid-utf8.ts": Buffer.from([0x61, 0xff, 0x62, 0x0a]),
  // Contains a NUL byte: fails the binary heuristic before decoding is even attempted.
  "src/binary-mistake.ts": Buffer.from([0x00, 0x01, 0x02]),
};

const EXPECTED_BUCKET: Record<string, string> = {
  "gui/src/icons.tsx": "Generated (icons, catalogues)",
  "tests/example.test.ts": "Tests",
  "electron/main.ts": "Desktop shell (Electron)",
  "gui/src/App.tsx": "Dashboard — source",
  "README.md": "Docs & prose (Markdown)",
  "config.json": "Config & manifests",
};

/** Files whose commit author is a known agent identity, so `agent` lines are pinned as non-zero rather than always zero. The rest come from the second, non-agent commit. */
const AGENT_AUTHORED_PATHS = new Set(["gui/src/icons.tsx", "electron/main.ts"]);

function writeFixtureFile(root: string, path: string, content: Buffer | string): void {
  const full = join(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

/**
 * A tiny synthetic repository with known content and two commits by two different authors —
 * one a known agent identity, one not — built fresh in a temp directory instead of scanning this
 * project's own tracked files. `core.autocrlf`/local identity are set explicitly rather than
 * relied on from the environment: `scripts/test.ts` sandboxes `HOME` for the whole suite, so
 * there is no guarantee a global `.gitconfig` with a user identity is visible here.
 */
function buildFixtureRepo(): { root: string; revision: string } {
  const root = mkdtempSync(join(tmpdir(), "count-lines-fixture-"));
  git(root, ["init", "-q"]);
  git(root, ["config", "user.name", "Fixture Author"]);
  git(root, ["config", "user.email", "fixture@example.invalid"]);
  git(root, ["config", "core.autocrlf", "false"]);
  git(root, ["config", "commit.gpgsign", "false"]);

  const claude = KNOWN_AGENT_IDENTITIES.find(identity => identity.name === "Claude Fable 5")!;

  for (const [path, lines] of Object.entries(FIXTURE_FILES)) {
    if (!AGENT_AUTHORED_PATHS.has(path)) continue;
    writeFixtureFile(root, path, `${lines.join("\n")}\n`);
  }
  git(root, ["add", "-A"]);
  git(root, ["commit", "-q", "-m", "agent commit", "--author", `${claude.name} <${claude.email}>`]);

  for (const [path, lines] of Object.entries(FIXTURE_FILES)) {
    if (AGENT_AUTHORED_PATHS.has(path)) continue;
    writeFixtureFile(root, path, `${lines.join("\n")}\n`);
  }
  for (const [path, bytes] of Object.entries(UNREADABLE_FILES)) writeFixtureFile(root, path, bytes);
  writeFixtureFile(root, "logo.png", Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x00, 0x01, 0x02]));
  git(root, ["add", "-A"]);
  git(root, ["commit", "-q", "-m", "person commit"]);

  const revision = spawnSync("git", ["rev-parse", "HEAD"], { cwd: root, encoding: "utf8" }).stdout.trim();
  return { root, revision };
}

let fixture: { root: string; revision: string };
let counted: Awaited<ReturnType<typeof countLines>>;
let attributed: Awaited<ReturnType<typeof countLinesWithAttribution>>;

beforeAll(async () => {
  fixture = buildFixtureRepo();
  counted = await countLines(fixture.revision, { root: fixture.root });
  // Pass the already-computed `counted` through so this does not run the tracked-file scan a
  // second time; `countLinesWithAttribution()` would otherwise call `countLines()` again
  // internally for the exact same revision.
  attributed = await countLinesWithAttribution(fixture.revision, counted);
});

afterAll(() => {
  rmSync(fixture.root, { recursive: true, force: true });
});

describe("release line attribution", () => {
  test("counts exactly the fixture's known content", () => {
    expect(counted.assets).toBe(1); // logo.png
    expect(counted.unreadable).toBe(Object.keys(UNREADABLE_FILES).length);
    expect(counted.totals.files).toBe(Object.keys(FIXTURE_FILES).length);

    for (const [path, lines] of Object.entries(FIXTURE_FILES)) {
      const entry = counted.entries.find(candidate => candidate.path === path);
      expect(entry, `expected a counted entry for ${path}`).toBeDefined();
      expect(entry!.name).toBe(EXPECTED_BUCKET[path]);
      expect(entry!.total).toBe(lines.length);
      expect(entry!.code).toBe(lines.filter(line => line.trim() !== "").length);
    }
  });

  test("keeps the release-ready row and table shape", () => {
    expect(attributed.rows.length).toBeGreaterThan(0);
    for (const row of attributed.rows) {
      expect(Object.keys(row).sort()).toEqual([
        "agent",
        "files",
        "name",
        "nonBlank",
        "people",
        "total",
      ]);
    }

    const table = formatLineAttributionTable(attributed);
    expect(table).toStartWith("| Area | Files | Lines | Non-blank | Agent | People |");
    expect(table).toContain("| **Project total (counted text)** |");
    expect(table).toContain("| **Grand total (tracked files)** |");
    expect(table).toContain("Surviving physical lines attributed with `git blame`");
    expect(table).toContain(attributed.revision);
  });

  test("keeps generated and excluded material explicit", () => {
    expect(attributed.rows.some(row => row.name.startsWith("Generated"))).toBe(true);
    expect(attributed.excluded.assets).toBe(counted.assets);
    expect(attributed.excluded.unreadable).toBe(counted.unreadable);

    const table = formatLineAttributionTable(attributed);
    expect(table).toContain("Excluded from line attribution");
    expect(table).toContain(`${attributed.excluded.assets.toLocaleString("en-US")} tracked assets`);
    expect(table).toContain("| Excluded — binary assets |");
    expect(table).toContain("| Excluded — unreadable text |");
  });

  test("attributes the agent-authored fixture files to the agent and the rest to people", () => {
    for (const [path, bucket] of Object.entries(EXPECTED_BUCKET)) {
      const row = attributed.rows.find(candidate => candidate.name === bucket)!;
      const expectAgent = AGENT_AUTHORED_PATHS.has(path);
      expect(
        { path, agent: row.agent, people: row.people },
        `${path} should be ${expectAgent ? "entirely agent-authored" : "entirely person-authored"} in its bucket`,
      ).toEqual({ path, agent: expectAgent ? row.total : 0, people: expectAgent ? 0 : row.total });
    }
    expect(attributed.totals.agent).toBeGreaterThan(0);
    expect(attributed.totals.people).toBeGreaterThan(0);
  });

  test("agent and people attribution equals every surviving physical line", () => {
    for (const row of attributed.rows) {
      expect({
        area: row.name,
        attributed: row.agent + row.people,
        survivingLines: row.total,
      }).toEqual({
        area: row.name,
        attributed: row.total,
        survivingLines: row.total,
      });
    }

    expect(attributed.totals.agent + attributed.totals.people).toBe(attributed.totals.total);
  });

  test("attribution cannot drift from the committed line counter", () => {
    const summed = attributed.rows.reduce(
      (sum, row) => ({
        files: sum.files + row.files,
        total: sum.total + row.total,
        nonBlank: sum.nonBlank + row.nonBlank,
        agent: sum.agent + row.agent,
        people: sum.people + row.people,
      }),
      { files: 0, total: 0, nonBlank: 0, agent: 0, people: 0 },
    );

    expect(summed).toEqual(attributed.totals);
    expect(attributed.totals.files).toBe(counted.totals.files);
    expect(attributed.totals.total).toBe(counted.totals.total);
    expect(attributed.totals.nonBlank).toBe(counted.totals.code);
    expect(attributed.rows.map(row => row.name)).toEqual(counted.rows.map(row => row.name));
  });

  test("uses exact author and co-author identities without fuzzy look-alikes", () => {
    const claude = KNOWN_AGENT_IDENTITIES.find(identity => identity.name === "Claude Fable 5")!;
    const codex = KNOWN_AGENT_IDENTITIES.find(identity => identity.name === "OpenAI Codex")!;
    expect(isAgentAttribution(
      { name: `  ${claude.name.replace(" ", "   ")} `, email: claude.email.toUpperCase() },
      [],
    )).toBe(true);
    expect(isAgentAttribution(
      { name: "A Person", email: "person@example.test" },
      [codex],
    )).toBe(true);
    for (const lookalike of EXCLUDED_AGENT_LOOKALIKES) {
      expect(isAgentAttribution(lookalike, [])).toBe(false);
    }
  });
});
