/**
 * The dashboard's icons are Material Symbols, and stay that way.
 *
 * This used to be a file of hand-drawn Lucide-style strokes. They were tidy and
 * internally consistent, which is exactly why nobody questioned them — the app
 * looked deliberate while disagreeing with the design prototype on five nav
 * glyphs at once. Approximating a published icon set by hand is the failure mode
 * this guards, because it never announces itself: an approximate icon renders
 * perfectly, passes every test, and is only wrong next to the real thing.
 *
 * So the shapes come from `scripts/gen-icons.ts`, which fetches them from
 * google/material-design-icons, and these assertions keep the generated file
 * generated. Adding one more "just this once" hand-drawn SVG is how the set
 * drifts back, one icon at a time.
 */

import { describe, expect, test } from "bun:test";

const ICONS = "gui/src/icons.tsx";
const GENERATOR = "scripts/gen-icons.ts";

const icons = await Bun.file(ICONS).text();
const generator = await Bun.file(GENERATOR).text();

/**
 * The only glyphs allowed to be hand-drawn, and the reason each one is.
 *
 * Three window controls, because Windows title-bar marks are OS chrome and a
 * filled Material glyph in that corner looks foreign on the platform it runs on.
 * One brand logo, because GitHub's mark is not in Material Symbols at all and a
 * generic substitute would point the user at the wrong idea of where a link goes.
 */
const HAND_DRAWN = ["IconWinMinimize", "IconWinMaximize", "IconWinRestore", "IconGithub"];

function exportedIcons(): string[] {
  return [...icons.matchAll(/^export const (Icon[A-Za-z]+)/gm)].map(m => m[1]);
}

describe("the icon set", () => {
  test("every icon is Material Symbols geometry, except the documented four", () => {
    // One assertion over the whole file rather than per-icon, so a new icon that
    // skips the generator shows up here by name instead of silently passing.
    const wrong: string[] = [];
    for (const [, name, body] of icons.matchAll(/^export const (Icon[A-Za-z]+) = \(p: P\) => \((.*?)\);/gm)) {
      if (HAND_DRAWN.includes(name)) {
        expect(`${name} uses the stroke helper: ${body.includes("{...SS(p)}")}`).toBe(`${name} uses the stroke helper: true`);
      } else if (!/\{\.\.\.S\(p, "/.test(body)) {
        wrong.push(name);
      }
    }
    expect(wrong).toEqual([]);
  });

  test("each icon's path data fits the grid its viewBox declares", () => {
    /**
     * Material Symbols ships two coordinate systems — `0 -960 960 960` for most
     * glyphs and a legacy `0 0 24 24` for some older files, which declare no
     * viewBox at all. Stamping the 960 grid onto 24-unit data draws the shape at
     * 1/40th scale in the corner, so it renders as nothing.
     *
     * That is a uniquely nasty failure: no error, no warning, no broken layout —
     * just an empty space where an icon should be. It shipped that way in the
     * Claude nav row and on the tab pin button before this check existed.
     */
    const offenders: string[] = [];
    for (const [, name, viewBox, body] of icons.matchAll(/^export const (Icon[A-Za-z]+) = \(p: P\) => \(<svg \{\.\.\.S\(p, "([^"]+)"\)\}>(.*?)<\/svg>\);/gm)) {
      // Fractions in path data are written without a leading zero, so `.5` has to
      // be matched explicitly or it reads as the integer 5.
      const largest = Math.max(...[...body.matchAll(/-?(?:\d+\.?\d*|\.\d+)/g)].map(m => Math.abs(Number(m[0]))));
      const bigGrid = viewBox.includes("960");
      if (bigGrid && largest < 100) offenders.push(`${name}: 960-grid viewBox but largest coordinate is ${largest}`);
      if (!bigGrid && largest > 100) offenders.push(`${name}: "${viewBox}" viewBox but a coordinate reaches ${largest}`);
    }
    expect(offenders).toEqual([]);
  });

  test("the hand-drawn exceptions are exactly the four the generator declares", () => {
    // Both lists have to agree. If someone adds a fifth exception to the
    // generator, this fails until they justify it here too — which is the point:
    // the exception list should be annoying to grow.
    const declared = [...generator.matchAll(/^  (Icon[A-Za-z]+): `<svg \{\.\.\.SS\(p\)\}/gm)].map(m => m[1]);
    expect(declared.sort()).toEqual([...HAND_DRAWN].sort());
  });

  test("the file still says it is generated", () => {
    // Losing this header is how a generated file gets hand-edited in good faith.
    expect(icons.startsWith("/* GENERATED by scripts/gen-icons.ts")).toBe(true);
  });

  test("no icon carries a stroke width the Material grid would distort", () => {
    // `strokeWidth` on a 960-unit viewBox renders a hairline or a blob depending
    // on the render size — a sign someone pasted 24-grid markup into a Material icon.
    for (const [, name, body] of icons.matchAll(/^export const (Icon[A-Za-z]+) = \(p: P\) => \((.*?)\);/gm)) {
      if (HAND_DRAWN.includes(name)) continue;
      expect(`${name} strokeWidth: ${body.includes("strokeWidth")}`).toBe(`${name} strokeWidth: false`);
    }
  });
});

describe("the nav matches the design prototype", () => {
  /**
   * The prototype names the glyph for every page in one table. The dashboard has
   * its own table naming a React component per page, and the generated icon file
   * records which glyph each component draws. Those three have to agree, and
   * nothing structural forces them to.
   *
   * This is not hypothetical. The first pass of the Material Symbols port mapped
   * components to glyphs by reading their names and picking what sounded right —
   * `IconRegex` to `regular_expression`, `IconChangelog` to `receipt_long` — and
   * got five of nineteen wrong while looking entirely plausible. The prototype
   * had said `rule` and `history_edu` all along, in a table nobody consulted.
   */
  const PROTOTYPE = "design/OpenCodex M3.dc.html";
  const PAGE_META = "gui/src/shell/page-meta.ts";

  test("every page the prototype names uses the prototype's glyph", async () => {
    const prototype = await Bun.file(PROTOTYPE).text();
    const meta = await Bun.file(PAGE_META).text();

    // page id -> glyph, straight from the prototype's PAGES table.
    const want = new Map(
      [...prototype.matchAll(/\{ id: "([a-z0-9-]+)", icon: "([a-z_]+)"/g)].map(m => [m[1], m[2]]),
    );
    expect(want.size).toBeGreaterThan(15);

    // component -> glyph, from the generated file's trailing comments.
    const glyphOf = new Map(
      [...icons.matchAll(/^export const (Icon[A-Za-z]+) = .*?\); \/\* ([a-z_]+) \*\/$/gm)].map(m => [m[1], m[2]]),
    );

    // page id -> component, from the dashboard's own table.
    const block = meta.slice(meta.indexOf("const ICONS"), meta.indexOf("const TKEYS"));
    const uses = new Map(
      [...block.matchAll(/^ +"?([a-z0-9-]+)"?: (Icon[A-Za-z]+),$/gm)].map(m => [m[1], m[2]]),
    );

    const mismatches: string[] = [];
    for (const [page, glyph] of want) {
      const component = uses.get(page);
      const actual = component ? glyphOf.get(component) : undefined;
      if (actual !== glyph) mismatches.push(`${page}: prototype wants "${glyph}", app draws "${actual}" (${component})`);
    }
    expect(mismatches).toEqual([]);
  });
});

describe("icon call sites", () => {
  test("every icon used in the dashboard is exported", async () => {
    // A missing export is a build error, but a *typo'd* one that happens to match
    // another icon is not — this catches the rename that half-landed.
    const exported = new Set(exportedIcons());
    const glob = new Bun.Glob("gui/src/**/*.tsx");
    const used = new Set<string>();

    for await (const path of glob.scan(".")) {
      if (path.replace(/\\/g, "/").endsWith("gui/src/icons.tsx")) continue;
      const source = await Bun.file(path).text();
      for (const [, name] of source.matchAll(/<(Icon[A-Za-z]+)[\s/>]/g)) used.add(name);
    }

    expect(used.size).toBeGreaterThan(20);
    expect([...used].filter(name => !exported.has(name))).toEqual([]);
  });
});
