/**
 * The in-app documentation browser.
 *
 * Every user-facing app has to ship its own offline documentation browser,
 * distinct from and in addition to the public documentation site's articles —
 * this is that browser, not a webview pointed at the site. The corpus is
 * bundled at build time (`docs/generated-articles.ts`, GENERATED by
 * `scripts/gen-docs-articles.ts` from the site's own plain-Markdown articles;
 * see that script and `scripts/docs-article-source.ts` for the full "which
 * articles, and why" story) so the whole thing works with the network
 * unplugged: no fetch anywhere in this file.
 *
 * Two panes: a searchable, categorized article list on the left, and a
 * reading pane on the right. Search is a single field over every bundled
 * article's title, description AND body — not just titles — wired to the same
 * anchored regex builder every other search bar in this app carries, plain
 * text by default. Clicking a link inside an article's rendered body that
 * points at another bundled article opens it right here, in the same pane,
 * through `Markdown`'s `onInternalLink` — never a new browser tab and never a
 * dead end silently doing nothing. A link that resolves outside the bundled
 * corpus (most often one of the `.mdx` pages this browser does not bundle)
 * gets an honest "not in this offline copy" state instead of pretending every
 * link in real prose lands somewhere.
 */

import { useMemo, useState } from "react";
import { DOCS_ARTICLES } from "../docs/generated-articles";
import { DOC_CATEGORY_ORDER, type DocArticle, type DocCategory } from "../docs/types";
import { resolveDocHref } from "../docs/link-resolution";
import Markdown, { type MarkdownLinkTarget } from "../shell/Markdown";
import { RegexBuilderButton } from "../shell/RegexBuilderButton";
import { SearchFlagsRow } from "../shell/SearchFlagsRow";
import { DEFAULT_SEARCH_FLAGS, settingsMatcher } from "../shell/settings-search";
import { Chip, Empty, TextInput } from "../shell/m3-ui";
import { IconSearch } from "../icons";
import { useT } from "../i18n/shared";
import type { TKey } from "../i18n/shared";

const CATEGORY_TKEY: Record<DocCategory, TKey> = {
  "getting-started": "docs.category.gettingStarted",
  guides: "docs.category.guides",
  reference: "docs.category.reference",
  troubleshooting: "docs.category.troubleshooting",
  general: "docs.category.general",
};

/**
 * How many articles seed the anchored builder's sample text. Bounded for the
 * same reason every other search bar in this app bounds its sample: the
 * engine caps what it evaluates anyway, and a host with dozens of long
 * articles should not hand the popover a small novel to try a pattern against.
 */
const SAMPLE_ARTICLES = 6;

/** Everything a search runs over for one article — title and description are
 * shown in the list; the body is included so a search genuinely reaches
 * article CONTENT, not just its heading, per the browser's own contract. */
function articleText(a: DocArticle): string {
  return `${a.title} ${a.description} ${a.body}`;
}

export default function Docs() {
  const t = useT();
  const [query, setQuery] = useState("");
  const [useRegex, setUseRegex] = useState(false);
  const [flags, setFlags] = useState(DEFAULT_SEARCH_FLAGS);
  const [selectedId, setSelectedId] = useState<string | null>(DOCS_ARTICLES[0]?.id ?? null);
  /** Set when a rendered link resolves outside the bundled corpus; cleared on any successful navigation. */
  const [notFoundHref, setNotFoundHref] = useState<string | null>(null);

  const { visible, regexError } = useMemo(() => {
    const matcher = settingsMatcher(query, useRegex, flags);
    if (matcher.error) return { visible: [] as DocArticle[], regexError: matcher.error };
    return { visible: DOCS_ARTICLES.filter(a => matcher.test(articleText(a))), regexError: null as string | null };
  }, [query, useRegex, flags]);

  const grouped = useMemo(() => {
    const byCategory = new Map<DocCategory, DocArticle[]>();
    for (const a of visible) {
      const list = byCategory.get(a.category);
      if (list) list.push(a); else byCategory.set(a.category, [a]);
    }
    return DOC_CATEGORY_ORDER
      .filter(c => byCategory.has(c))
      .map(category => ({ category, articles: byCategory.get(category)! }));
  }, [visible]);

  // The search narrows the LIST, not the open article — exactly like every
  // other collection search bar in this app leaves the current selection
  // alone until the user actually clicks a different row. Typing a query that
  // (temporarily) filters the open article out of the visible list must not
  // yank the reading pane out from under someone mid-read.
  const selected = useMemo(() => DOCS_ARTICLES.find(a => a.id === selectedId) ?? null, [selectedId]);

  const sample = useMemo(
    () => DOCS_ARTICLES.slice(0, SAMPLE_ARTICLES).map(articleText).join("\n"),
    [],
  );

  const openArticle = (id: string, anchor: string | null) => {
    setSelectedId(id);
    setNotFoundHref(null);
    if (anchor) {
      // Two frames: one for React to commit the new article's markup, one for
      // the browser to have laid it out, so the target heading actually
      // exists at the id `slugifyHeading` gave it before the scroll runs.
      // `requestAnimationFrame` — with the same `setTimeout` fallback
      // `CommandPalette.tsx`'s own scheduler uses — because not every
      // environment this runs in (the test harness among them) carries it.
      const raf: (run: () => void) => void = typeof requestAnimationFrame === "function"
        ? cb => requestAnimationFrame(cb)
        : cb => { setTimeout(cb, 16); };
      raf(() => raf(() => {
        document.getElementById(anchor)?.scrollIntoView({ block: "start" });
      }));
    }
  };

  const handleInternalLink = (target: MarkdownLinkTarget) => {
    if (!selected) return;
    const resolved = resolveDocHref(target.href, selected);
    const match = resolved.id ? DOCS_ARTICLES.find(a => a.id === resolved.id) : undefined;
    if (match) openArticle(match.id, resolved.anchor);
    else setNotFoundHref(target.href);
  };

  return (
    <>
      <p className="m3-page-lead">{t("docs.subtitle")}</p>

      <div className="m3-docs-root">
        <nav className="m3-docs-nav" aria-label={t("docs.navAria")}>
          <div className="m3-row" role="search">
            <IconSearch width={20} height={20} aria-hidden="true" />
            <TextInput
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder={t("docs.search")}
              aria-label={t("docs.search")}
              aria-invalid={!!regexError}
              style={{ flex: "1 1 auto", minWidth: 0, width: "auto" }}
            />
            {/* Plain text stays the default; `.*` is an explicit opt-in, exactly
                like every other search bar in this app. */}
            <Chip selected={useRegex} onClick={() => setUseRegex(v => !v)} title={t("search.regexHint")} aria-label={t("regex.regexMode")}>
              <code style={{ fontFamily: "var(--mono)" }}>.*</code>
            </Chip>
            <RegexBuilderButton
              value={query}
              onApply={(pattern, appliedFlags) => { setQuery(pattern); setFlags(appliedFlags); }}
              regex={useRegex}
              onRegexChange={setUseRegex}
              flags={flags}
              sample={sample}
              label={t("docs.openBuilder")}
              dialogLabel={t("docs.openBuilder")}
            />
          </div>

          {regexError && (
            <p role="alert" className="m3-docs-error">{t("regex.invalid")}: {regexError}</p>
          )}
          <SearchFlagsRow regex={useRegex} flags={flags} onFlagsChange={setFlags} id="docs-flags-state" />

          <p className="m3-docs-count">
            {t("docs.articleCount", { count: String(visible.length), total: String(DOCS_ARTICLES.length) })}
          </p>

          {grouped.length === 0 ? (
            <Empty title={t("docs.noResults")}>{t("docs.noResultsBody")}</Empty>
          ) : (
            grouped.map(({ category, articles }) => (
              <div key={category} className="m3-docs-group">
                <h3 className="m3-docs-group-title">{t(CATEGORY_TKEY[category])}</h3>
                <ul className="m3-docs-list">
                  {articles.map(a => (
                    <li key={a.id}>
                      <button
                        type="button"
                        className={`m3-docs-item${a.id === selectedId ? " m3-docs-item--active" : ""}`}
                        aria-current={a.id === selectedId ? "page" : undefined}
                        onClick={() => openArticle(a.id, null)}
                      >
                        <span className="m3-docs-item-title">{a.title}</span>
                        {a.description && <span className="m3-docs-item-desc">{a.description}</span>}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            ))
          )}
        </nav>

        <div className="m3-docs-article">
          {notFoundHref ? (
            <Empty title={t("docs.linkNotFound")}>{t("docs.linkNotFoundBody", { href: notFoundHref })}</Empty>
          ) : selected ? (
            <article aria-labelledby="m3-docs-article-title">
              <h1 id="m3-docs-article-title" className="m3-docs-title">{selected.title}</h1>
              {selected.description && <p className="m3-docs-desc">{selected.description}</p>}
              <div className="m3-md">
                <Markdown text={selected.body} onInternalLink={handleInternalLink} idPrefix={selected.id} />
              </div>
            </article>
          ) : (
            <Empty title={t("docs.empty")}>{t("docs.emptyBody")}</Empty>
          )}
        </div>
      </div>
    </>
  );
}
