/**
 * Copy for the appearance system: the element editor, the colour picker, the
 * font picker and the presets.
 *
 * A separate table from `strings.ts`, and it is meant to stop being one. That
 * module is the site's dictionary and this surface's keys belong in it; they are
 * here because it was being written by another stage at the same moment, and
 * two agents rewriting one 47 KB file is how a locale loses half its keys.
 *
 * So the lookup below is built to make the merge a *deletion*: `appearanceT`
 * asks `strings.ts` first and only falls through to the table here when that
 * table has no answer. Move these entries into `EN`/`KO`/`ZH`/`RU`/`JA` there
 * and every call site keeps working unchanged; then this file's `TABLE` can go
 * without touching a component. Nothing imports the table directly, only the
 * translator, which is what makes that true.
 *
 * Same flat dotted keys and the same `TFn` shape as `strings.ts`, so the two are
 * interchangeable at every call site. Same fallback discipline too: an unknown
 * key renders its last dotted segment rather than an empty string, because a
 * label reading `letterSpacing` is obviously wrong on sight while an empty one
 * looks like a control that simply has no name.
 *
 * These are the five *documentation locales*. The English / playful Cantonese /
 * bilingual language modes and the funny-level sliders are a different axis,
 * owned by the i18n stage, and layer on top of this rather than replacing it.
 */

import { fmt, stringsFor, type StringsLocale, type TFn } from "./strings";

const EN = {
  /* ---- the editor itself ------------------------------------------------ */
  "ap.edit": "Edit appearance…",
  "ap.editThis": "Edit appearance of this element",
  "ap.editOf": "Edit appearance of {name}",
  "ap.title": "Appearance — {name}",
  "ap.close": "Close appearance editor",
  "ap.containers": "Containing elements",
  "ap.applies": "Applies to every {name} on the site.",
  "ap.preview": "Preview",
  "ap.previewText": "Aa Bb Cc 0123 — 廣東話 · 한국어 · 日本語 · Русский",
  "ap.secText": "Text",
  "ap.secBox": "Box",
  "ap.secPresets": "Presets",
  "ap.reset": "Reset",
  "ap.resetOne": "Reset {name}",
  "ap.resetElement": "Reset this element",
  "ap.resetAll": "Reset every element",
  "ap.resetAllConfirm": "Reset the appearance of every element on the site? Your theme, language and tabs are not affected.",
  "ap.inherits": "Inherits",
  "ap.none": "None",
  "ap.default": "Default",
  "ap.customized": "{count} element(s) customized",
  "ap.keyboardHint": "Shift + right-click any element to open this editor directly.",
  "ap.saved": "Saved",
  "ap.use": "Use",

  /* ---- colour ----------------------------------------------------------- */
  "color.open": "Choose a colour",
  "color.title": "Colour",
  "color.field": "Chroma and lightness",
  "color.fieldHint": "Drag, or use the arrow keys. Page Up/Down moves in larger steps.",
  "color.hue": "Hue",
  "color.chroma": "Chroma",
  "color.lightness": "Lightness",
  "color.alpha": "Opacity",
  "color.value": "Value",
  "color.valueHint": "Any CSS colour: a name, #hex, rgb(), hsl(), lab(), oklch(), device-cmyk().",
  "color.invalid": "Not a colour this can read. The previous value is still applied.",
  "color.translator": "This colour in every space",
  "color.copy": "Copy {space}",
  "color.copied": "Copied",
  "color.gamut": "Gamut",
  "color.clip": "Outside sRGB. Written as oklch() so a wide-gamut display shows it; anywhere else it is clipped to the nearest sRGB colour.",
  "color.clipFar": "Well outside sRGB. Most displays will show a noticeably different colour.",
  "color.contrast": "Contrast",
  "color.contrastAgainst": "against {name}",
  "color.contrastSurface": "the page",
  "color.contrastText": "the text",
  "color.eyedropper": "Pick from the screen",
  "color.eyedropperNo": "This browser has no screen colour picker.",
  "color.recent": "Recent",
  "color.swatches": "Theme colours",
  "color.clear": "Clear the colour",
  "color.spectrum": "Hue spectrum",

  /* ---- fonts ------------------------------------------------------------ */
  "font.family": "Typeface",
  "font.search": "Search typefaces",
  "font.searchPh": "Search typefaces",
  "font.installed": "Use my installed fonts",
  "font.installedHint": "Asks the browser for permission to list every font on this machine.",
  "font.probed": "Measured list",
  "font.local": "Installed fonts",
  "font.bundled": "Bundled only",
  "font.noMatch": "No typeface matches.",
  "font.custom": "Or type any family name",
  "font.customPh": "e.g. Iosevka",
  "font.faces": "{count} faces",
  "font.axes": "Variable axes",
  "font.axesNone": "This typeface has no variable axes.",
  "font.axesUnknown": "Variable axes could not be read for this typeface.",
  "font.sample": "Handgloves 廣東話",

  /* ---- typography ------------------------------------------------------- */
  "type.size": "Size",
  "type.weight": "Weight",
  "type.slant": "Style",
  "type.italic": "Italic",
  "type.oblique": "Oblique",
  "type.obliqueAngle": "Oblique angle",
  "type.underline": "Underline",
  "type.underlineColor": "Underline colour",
  "type.underlineThickness": "Underline thickness",
  "type.strike": "Strikethrough",
  "type.strikeSingle": "Single",
  "type.strikeDouble": "Double",
  "type.overline": "Overline",
  "type.caps": "Capitalization",
  "type.upper": "UPPERCASE",
  "type.lower": "lowercase",
  "type.capitalize": "Capitalize Each Word",
  "type.smallCaps": "Small caps",
  "type.allSmallCaps": "All small caps",
  "type.script": "Position",
  "type.super": "Superscript",
  "type.sub": "Subscript",
  "type.color": "Text colour",
  "type.highlight": "Highlight",
  "type.outline": "Outline width",
  "type.outlineColor": "Outline colour",
  "type.shadow": "Shadow",
  "type.shadowX": "Shadow across",
  "type.shadowY": "Shadow down",
  "type.shadowBlur": "Shadow blur",
  "type.shadowColor": "Shadow colour",
  "type.glow": "Glow",
  "type.glowColor": "Glow colour",
  "type.letterSpacing": "Character spacing",
  "type.wordSpacing": "Word spacing",
  "type.lineHeight": "Line height",
  "type.baseline": "Baseline offset",
  "type.direction": "Text direction",
  "type.ltr": "Left to right",
  "type.rtl": "Right to left",
  "type.align": "Alignment",
  "type.alignStart": "Start",
  "type.alignCenter": "Centre",
  "type.alignEnd": "End",
  "type.alignJustify": "Justify",
  "type.maps": "Renders as {css}",
  "type.unsupported": "This browser does not support {css}. The control stays available and the value is kept, but nothing will change on screen here.",
  "type.partial": "Limitation: {caveat}",
  "type.unknown": "Support for {css} could not be checked in this browser.",

  /* ---- box -------------------------------------------------------------- */
  "box.bg": "Background",
  "box.radius": "Corner radius",
  "box.pad": "Padding",
  "box.border": "Border width",
  "box.borderColor": "Border colour",
  "box.borderStyle": "Border style",
  "box.elevation": "Elevation",
  "box.opacity": "Opacity",
  "box.solid": "Solid",
  "box.dashed": "Dashed",
  "box.dotted": "Dotted",
  "box.double": "Double",

  /* ---- presets ---------------------------------------------------------- */
  "preset.title": "Saved appearances",
  "preset.name": "Preset name",
  "preset.namePh": "e.g. High contrast",
  "preset.save": "Save current appearance",
  "preset.apply": "Apply {name}",
  "preset.delete": "Delete {name}",
  "preset.export": "Export…",
  "preset.import": "Import…",
  "preset.none": "No saved appearances yet.",
  "preset.importedOne": "Imported {count} preset(s).",
  "preset.importFailed": "That file holds no appearance preset this can read.",
  "preset.applied": "Applied {name}.",
  "preset.includes": "A preset carries the theme, seed colour, density, typography and every per-element style.",

  /* ---- the anchored regex builder beside every search field -------------- */
  "rx.open": "Build a pattern",
  "rx.title": "Regular expression",
  "rx.mode": "Match with",
  "rx.plain": "Plain text",
  "rx.regex": "Regex",
  "rx.pattern": "Pattern",
  "rx.flags": "Flags",
  "rx.sample": "Sample text",
  "rx.matches": "{count} match(es)",
  "rx.noMatches": "No matches.",
  "rx.truncated": "Showing the first matches only.",
  "rx.groups": "Capture groups",
  "rx.invalid": "Invalid pattern: {error}",
  "rx.engine": "JavaScript (ECMAScript) RegExp, evaluated in this page. Nothing is sent anywhere.",
  "rx.insert": "Insert {token}",
  "rx.apply": "Use this pattern",
  "rx.close": "Close the pattern builder",
} as const;

type Key = keyof typeof EN;
type Table = Record<Key, string>;

const KO: Table = {
  "ap.edit": "모양 편집…",
  "ap.editThis": "이 요소의 모양 편집",
  "ap.editOf": "{name} 모양 편집",
  "ap.title": "모양 — {name}",
  "ap.close": "모양 편집기 닫기",
  "ap.containers": "상위 요소",
  "ap.applies": "사이트의 모든 {name}에 적용됩니다.",
  "ap.preview": "미리보기",
  "ap.previewText": "Aa Bb Cc 0123 — 廣東話 · 한국어 · 日本語 · Русский",
  "ap.secText": "텍스트",
  "ap.secBox": "박스",
  "ap.secPresets": "프리셋",
  "ap.reset": "초기화",
  "ap.resetOne": "{name} 초기화",
  "ap.resetElement": "이 요소 초기화",
  "ap.resetAll": "모든 요소 초기화",
  "ap.resetAllConfirm": "사이트의 모든 요소 모양을 초기화할까요? 테마, 언어, 탭은 영향을 받지 않습니다.",
  "ap.inherits": "상속",
  "ap.none": "없음",
  "ap.default": "기본값",
  "ap.customized": "{count}개 요소 사용자 지정됨",
  "ap.keyboardHint": "Shift + 마우스 오른쪽 클릭으로 이 편집기를 바로 엽니다.",
  "ap.saved": "저장됨",
  "ap.use": "사용",

  "color.open": "색 선택",
  "color.title": "색",
  "color.field": "채도와 밝기",
  "color.fieldHint": "드래그하거나 방향키를 사용하세요. Page Up/Down은 크게 이동합니다.",
  "color.hue": "색상",
  "color.chroma": "채도",
  "color.lightness": "밝기",
  "color.alpha": "불투명도",
  "color.value": "값",
  "color.valueHint": "모든 CSS 색: 이름, #hex, rgb(), hsl(), lab(), oklch(), device-cmyk().",
  "color.invalid": "읽을 수 없는 색입니다. 이전 값이 그대로 적용됩니다.",
  "color.translator": "모든 색 공간에서의 이 색",
  "color.copy": "{space} 복사",
  "color.copied": "복사됨",
  "color.gamut": "색역",
  "color.clip": "sRGB 밖입니다. oklch()로 기록되어 광색역 디스플레이에서는 그대로 보이고, 그 외에는 가장 가까운 sRGB 색으로 잘립니다.",
  "color.clipFar": "sRGB에서 크게 벗어났습니다. 대부분의 화면에서 눈에 띄게 다른 색으로 보입니다.",
  "color.contrast": "대비",
  "color.contrastAgainst": "{name} 대비",
  "color.contrastSurface": "페이지",
  "color.contrastText": "텍스트",
  "color.eyedropper": "화면에서 색 추출",
  "color.eyedropperNo": "이 브라우저에는 화면 색 추출기가 없습니다.",
  "color.recent": "최근",
  "color.swatches": "테마 색",
  "color.clear": "색 지우기",
  "color.spectrum": "색상 스펙트럼",

  "font.family": "글꼴",
  "font.search": "글꼴 검색",
  "font.searchPh": "글꼴 검색",
  "font.installed": "설치된 글꼴 사용",
  "font.installedHint": "이 컴퓨터의 모든 글꼴을 나열하도록 브라우저에 권한을 요청합니다.",
  "font.probed": "측정된 목록",
  "font.local": "설치된 글꼴",
  "font.bundled": "번들 글꼴만",
  "font.noMatch": "일치하는 글꼴이 없습니다.",
  "font.custom": "또는 글꼴 이름을 직접 입력",
  "font.customPh": "예: Iosevka",
  "font.faces": "{count}개 서체",
  "font.axes": "가변 축",
  "font.axesNone": "이 글꼴에는 가변 축이 없습니다.",
  "font.axesUnknown": "이 글꼴의 가변 축을 읽을 수 없습니다.",
  "font.sample": "Handgloves 廣東話",

  "type.size": "크기",
  "type.weight": "굵기",
  "type.slant": "스타일",
  "type.italic": "이탤릭",
  "type.oblique": "오블리크",
  "type.obliqueAngle": "오블리크 각도",
  "type.underline": "밑줄",
  "type.underlineColor": "밑줄 색",
  "type.underlineThickness": "밑줄 두께",
  "type.strike": "취소선",
  "type.strikeSingle": "한 줄",
  "type.strikeDouble": "두 줄",
  "type.overline": "윗줄",
  "type.caps": "대소문자",
  "type.upper": "대문자",
  "type.lower": "소문자",
  "type.capitalize": "단어 첫 글자 대문자",
  "type.smallCaps": "작은 대문자",
  "type.allSmallCaps": "전체 작은 대문자",
  "type.script": "위치",
  "type.super": "위 첨자",
  "type.sub": "아래 첨자",
  "type.color": "글자 색",
  "type.highlight": "형광펜",
  "type.outline": "윤곽선 두께",
  "type.outlineColor": "윤곽선 색",
  "type.shadow": "그림자",
  "type.shadowX": "그림자 가로",
  "type.shadowY": "그림자 세로",
  "type.shadowBlur": "그림자 흐림",
  "type.shadowColor": "그림자 색",
  "type.glow": "발광",
  "type.glowColor": "발광 색",
  "type.letterSpacing": "자간",
  "type.wordSpacing": "단어 간격",
  "type.lineHeight": "행간",
  "type.baseline": "기준선 오프셋",
  "type.direction": "글자 방향",
  "type.ltr": "왼쪽에서 오른쪽",
  "type.rtl": "오른쪽에서 왼쪽",
  "type.align": "정렬",
  "type.alignStart": "시작",
  "type.alignCenter": "가운데",
  "type.alignEnd": "끝",
  "type.alignJustify": "양쪽",
  "type.maps": "{css}로 렌더링됩니다",
  "type.unsupported": "이 브라우저는 {css}를 지원하지 않습니다. 컨트롤은 그대로 두고 값도 보관하지만 화면에는 반영되지 않습니다.",
  "type.partial": "제한: {caveat}",
  "type.unknown": "이 브라우저에서 {css} 지원 여부를 확인할 수 없습니다.",

  "box.bg": "배경",
  "box.radius": "모서리 둥글기",
  "box.pad": "안쪽 여백",
  "box.border": "테두리 두께",
  "box.borderColor": "테두리 색",
  "box.borderStyle": "테두리 스타일",
  "box.elevation": "그림자 단계",
  "box.opacity": "불투명도",
  "box.solid": "실선",
  "box.dashed": "파선",
  "box.dotted": "점선",
  "box.double": "이중선",

  "preset.title": "저장된 모양",
  "preset.name": "프리셋 이름",
  "preset.namePh": "예: 고대비",
  "preset.save": "현재 모양 저장",
  "preset.apply": "{name} 적용",
  "preset.delete": "{name} 삭제",
  "preset.export": "내보내기…",
  "preset.import": "가져오기…",
  "preset.none": "저장된 모양이 없습니다.",
  "preset.importedOne": "프리셋 {count}개를 가져왔습니다.",
  "preset.importFailed": "이 파일에는 읽을 수 있는 모양 프리셋이 없습니다.",
  "preset.applied": "{name}을(를) 적용했습니다.",
  "preset.includes": "프리셋에는 테마, 시드 색, 밀도, 타이포그래피, 모든 요소별 스타일이 포함됩니다.",

  "rx.open": "패턴 만들기",
  "rx.title": "정규식",
  "rx.mode": "일치 방식",
  "rx.plain": "일반 텍스트",
  "rx.regex": "정규식",
  "rx.pattern": "패턴",
  "rx.flags": "플래그",
  "rx.sample": "샘플 텍스트",
  "rx.matches": "{count}개 일치",
  "rx.noMatches": "일치 항목이 없습니다.",
  "rx.truncated": "처음 일치 항목만 표시합니다.",
  "rx.groups": "캡처 그룹",
  "rx.invalid": "잘못된 패턴: {error}",
  "rx.engine": "이 페이지에서 실행되는 JavaScript(ECMAScript) RegExp입니다. 아무것도 전송되지 않습니다.",
  "rx.insert": "{token} 삽입",
  "rx.apply": "이 패턴 사용",
  "rx.close": "패턴 빌더 닫기",
};

const ZH: Table = {
  "ap.edit": "编辑外观…",
  "ap.editThis": "编辑此元素的外观",
  "ap.editOf": "编辑 {name} 的外观",
  "ap.title": "外观 — {name}",
  "ap.close": "关闭外观编辑器",
  "ap.containers": "上级元素",
  "ap.applies": "应用于站点上的所有 {name}。",
  "ap.preview": "预览",
  "ap.previewText": "Aa Bb Cc 0123 — 廣東話 · 한국어 · 日本語 · Русский",
  "ap.secText": "文字",
  "ap.secBox": "盒子",
  "ap.secPresets": "预设",
  "ap.reset": "重置",
  "ap.resetOne": "重置{name}",
  "ap.resetElement": "重置此元素",
  "ap.resetAll": "重置所有元素",
  "ap.resetAllConfirm": "重置站点上所有元素的外观？主题、语言和标签页不受影响。",
  "ap.inherits": "继承",
  "ap.none": "无",
  "ap.default": "默认",
  "ap.customized": "已自定义 {count} 个元素",
  "ap.keyboardHint": "Shift + 右键点击任意元素可直接打开此编辑器。",
  "ap.saved": "已保存",
  "ap.use": "使用",

  "color.open": "选择颜色",
  "color.title": "颜色",
  "color.field": "彩度与明度",
  "color.fieldHint": "拖动，或使用方向键。Page Up/Down 大步移动。",
  "color.hue": "色相",
  "color.chroma": "彩度",
  "color.lightness": "明度",
  "color.alpha": "不透明度",
  "color.value": "值",
  "color.valueHint": "任意 CSS 颜色：名称、#hex、rgb()、hsl()、lab()、oklch()、device-cmyk()。",
  "color.invalid": "无法解析为颜色。仍沿用先前的值。",
  "color.translator": "该颜色在各色彩空间中的写法",
  "color.copy": "复制 {space}",
  "color.copied": "已复制",
  "color.gamut": "色域",
  "color.clip": "超出 sRGB。写作 oklch()，广色域显示器可正确呈现；其他设备会截断到最接近的 sRGB 颜色。",
  "color.clipFar": "远超 sRGB。多数屏幕会显示明显不同的颜色。",
  "color.contrast": "对比度",
  "color.contrastAgainst": "相对于{name}",
  "color.contrastSurface": "页面",
  "color.contrastText": "文字",
  "color.eyedropper": "从屏幕取色",
  "color.eyedropperNo": "此浏览器没有屏幕取色器。",
  "color.recent": "最近",
  "color.swatches": "主题色",
  "color.clear": "清除颜色",
  "color.spectrum": "色相光谱",

  "font.family": "字体",
  "font.search": "搜索字体",
  "font.searchPh": "搜索字体",
  "font.installed": "使用我已安装的字体",
  "font.installedHint": "向浏览器申请权限以列出本机的全部字体。",
  "font.probed": "探测所得列表",
  "font.local": "已安装字体",
  "font.bundled": "仅内置字体",
  "font.noMatch": "没有匹配的字体。",
  "font.custom": "或直接输入字体名称",
  "font.customPh": "例如 Iosevka",
  "font.faces": "{count} 种字形",
  "font.axes": "可变轴",
  "font.axesNone": "此字体没有可变轴。",
  "font.axesUnknown": "无法读取此字体的可变轴。",
  "font.sample": "Handgloves 廣東話",

  "type.size": "字号",
  "type.weight": "字重",
  "type.slant": "样式",
  "type.italic": "斜体",
  "type.oblique": "倾斜",
  "type.obliqueAngle": "倾斜角度",
  "type.underline": "下划线",
  "type.underlineColor": "下划线颜色",
  "type.underlineThickness": "下划线粗细",
  "type.strike": "删除线",
  "type.strikeSingle": "单线",
  "type.strikeDouble": "双线",
  "type.overline": "上划线",
  "type.caps": "大小写",
  "type.upper": "全大写",
  "type.lower": "全小写",
  "type.capitalize": "首字母大写",
  "type.smallCaps": "小型大写",
  "type.allSmallCaps": "全部小型大写",
  "type.script": "位置",
  "type.super": "上标",
  "type.sub": "下标",
  "type.color": "文字颜色",
  "type.highlight": "突出显示",
  "type.outline": "描边宽度",
  "type.outlineColor": "描边颜色",
  "type.shadow": "阴影",
  "type.shadowX": "阴影水平",
  "type.shadowY": "阴影垂直",
  "type.shadowBlur": "阴影模糊",
  "type.shadowColor": "阴影颜色",
  "type.glow": "辉光",
  "type.glowColor": "辉光颜色",
  "type.letterSpacing": "字符间距",
  "type.wordSpacing": "单词间距",
  "type.lineHeight": "行高",
  "type.baseline": "基线偏移",
  "type.direction": "文字方向",
  "type.ltr": "从左到右",
  "type.rtl": "从右到左",
  "type.align": "对齐",
  "type.alignStart": "起始",
  "type.alignCenter": "居中",
  "type.alignEnd": "末尾",
  "type.alignJustify": "两端对齐",
  "type.maps": "渲染为 {css}",
  "type.unsupported": "此浏览器不支持 {css}。控件保持可用且会保存该值，但此处不会有视觉变化。",
  "type.partial": "限制：{caveat}",
  "type.unknown": "无法在此浏览器中检测 {css} 的支持情况。",

  "box.bg": "背景",
  "box.radius": "圆角",
  "box.pad": "内边距",
  "box.border": "边框宽度",
  "box.borderColor": "边框颜色",
  "box.borderStyle": "边框样式",
  "box.elevation": "高度阴影",
  "box.opacity": "不透明度",
  "box.solid": "实线",
  "box.dashed": "虚线",
  "box.dotted": "点线",
  "box.double": "双线",

  "preset.title": "已保存的外观",
  "preset.name": "预设名称",
  "preset.namePh": "例如 高对比度",
  "preset.save": "保存当前外观",
  "preset.apply": "应用 {name}",
  "preset.delete": "删除 {name}",
  "preset.export": "导出…",
  "preset.import": "导入…",
  "preset.none": "尚未保存任何外观。",
  "preset.importedOne": "已导入 {count} 个预设。",
  "preset.importFailed": "该文件不包含可读取的外观预设。",
  "preset.applied": "已应用 {name}。",
  "preset.includes": "预设包含主题、种子色、密度、排版以及每个元素的样式。",

  "rx.open": "构建模式",
  "rx.title": "正则表达式",
  "rx.mode": "匹配方式",
  "rx.plain": "纯文本",
  "rx.regex": "正则",
  "rx.pattern": "模式",
  "rx.flags": "标志",
  "rx.sample": "示例文本",
  "rx.matches": "{count} 处匹配",
  "rx.noMatches": "没有匹配。",
  "rx.truncated": "仅显示前若干处匹配。",
  "rx.groups": "捕获组",
  "rx.invalid": "无效模式：{error}",
  "rx.engine": "在本页面执行的 JavaScript (ECMAScript) RegExp。不会发送任何内容。",
  "rx.insert": "插入 {token}",
  "rx.apply": "使用此模式",
  "rx.close": "关闭模式构建器",
};

const RU: Table = {
  "ap.edit": "Изменить оформление…",
  "ap.editThis": "Изменить оформление этого элемента",
  "ap.editOf": "Изменить оформление: {name}",
  "ap.title": "Оформление — {name}",
  "ap.close": "Закрыть редактор оформления",
  "ap.containers": "Родительские элементы",
  "ap.applies": "Применяется ко всем элементам «{name}» на сайте.",
  "ap.preview": "Предпросмотр",
  "ap.previewText": "Aa Bb Cc 0123 — 廣東話 · 한국어 · 日本語 · Русский",
  "ap.secText": "Текст",
  "ap.secBox": "Блок",
  "ap.secPresets": "Пресеты",
  "ap.reset": "Сбросить",
  "ap.resetOne": "Сбросить: {name}",
  "ap.resetElement": "Сбросить этот элемент",
  "ap.resetAll": "Сбросить все элементы",
  "ap.resetAllConfirm": "Сбросить оформление всех элементов сайта? Тема, язык и вкладки не затрагиваются.",
  "ap.inherits": "Наследуется",
  "ap.none": "Нет",
  "ap.default": "По умолчанию",
  "ap.customized": "Изменено элементов: {count}",
  "ap.keyboardHint": "Shift + правый клик по любому элементу открывает этот редактор сразу.",
  "ap.saved": "Сохранено",
  "ap.use": "Применить",

  "color.open": "Выбрать цвет",
  "color.title": "Цвет",
  "color.field": "Насыщенность и светлота",
  "color.fieldHint": "Перетащите или используйте стрелки. Page Up/Down — крупный шаг.",
  "color.hue": "Тон",
  "color.chroma": "Насыщенность",
  "color.lightness": "Светлота",
  "color.alpha": "Непрозрачность",
  "color.value": "Значение",
  "color.valueHint": "Любой цвет CSS: имя, #hex, rgb(), hsl(), lab(), oklch(), device-cmyk().",
  "color.invalid": "Это не читаемый цвет. Прежнее значение осталось в силе.",
  "color.translator": "Этот цвет во всех пространствах",
  "color.copy": "Скопировать {space}",
  "color.copied": "Скопировано",
  "color.gamut": "Охват",
  "color.clip": "За пределами sRGB. Записывается как oklch(), поэтому широкоохватный дисплей покажет его точно; в остальных случаях цвет обрежется до ближайшего sRGB.",
  "color.clipFar": "Далеко за пределами sRGB. На большинстве экранов цвет будет заметно другим.",
  "color.contrast": "Контраст",
  "color.contrastAgainst": "относительно: {name}",
  "color.contrastSurface": "страница",
  "color.contrastText": "текст",
  "color.eyedropper": "Взять цвет с экрана",
  "color.eyedropperNo": "В этом браузере нет экранной пипетки.",
  "color.recent": "Недавние",
  "color.swatches": "Цвета темы",
  "color.clear": "Очистить цвет",
  "color.spectrum": "Спектр тонов",

  "font.family": "Гарнитура",
  "font.search": "Поиск гарнитур",
  "font.searchPh": "Поиск гарнитур",
  "font.installed": "Использовать установленные шрифты",
  "font.installedHint": "Запрашивает у браузера разрешение перечислить все шрифты на этом компьютере.",
  "font.probed": "Список по замерам",
  "font.local": "Установленные шрифты",
  "font.bundled": "Только встроенные",
  "font.noMatch": "Ничего не найдено.",
  "font.custom": "Или впишите название гарнитуры",
  "font.customPh": "например Iosevka",
  "font.faces": "начертаний: {count}",
  "font.axes": "Переменные оси",
  "font.axesNone": "У этой гарнитуры нет переменных осей.",
  "font.axesUnknown": "Переменные оси этой гарнитуры прочитать не удалось.",
  "font.sample": "Handgloves Ёжик 廣東話",

  "type.size": "Размер",
  "type.weight": "Насыщенность",
  "type.slant": "Начертание",
  "type.italic": "Курсив",
  "type.oblique": "Наклонное",
  "type.obliqueAngle": "Угол наклона",
  "type.underline": "Подчёркивание",
  "type.underlineColor": "Цвет подчёркивания",
  "type.underlineThickness": "Толщина подчёркивания",
  "type.strike": "Зачёркивание",
  "type.strikeSingle": "Одинарное",
  "type.strikeDouble": "Двойное",
  "type.overline": "Надчёркивание",
  "type.caps": "Регистр",
  "type.upper": "ПРОПИСНЫЕ",
  "type.lower": "строчные",
  "type.capitalize": "Каждое Слово С Заглавной",
  "type.smallCaps": "Капитель",
  "type.allSmallCaps": "Полная капитель",
  "type.script": "Положение",
  "type.super": "Верхний индекс",
  "type.sub": "Нижний индекс",
  "type.color": "Цвет текста",
  "type.highlight": "Заливка",
  "type.outline": "Толщина обводки",
  "type.outlineColor": "Цвет обводки",
  "type.shadow": "Тень",
  "type.shadowX": "Тень по горизонтали",
  "type.shadowY": "Тень по вертикали",
  "type.shadowBlur": "Размытие тени",
  "type.shadowColor": "Цвет тени",
  "type.glow": "Свечение",
  "type.glowColor": "Цвет свечения",
  "type.letterSpacing": "Межбуквенный интервал",
  "type.wordSpacing": "Межсловный интервал",
  "type.lineHeight": "Межстрочный интервал",
  "type.baseline": "Смещение базовой линии",
  "type.direction": "Направление текста",
  "type.ltr": "Слева направо",
  "type.rtl": "Справа налево",
  "type.align": "Выравнивание",
  "type.alignStart": "К началу",
  "type.alignCenter": "По центру",
  "type.alignEnd": "К концу",
  "type.alignJustify": "По ширине",
  "type.maps": "Отображается как {css}",
  "type.unsupported": "Этот браузер не поддерживает {css}. Элемент управления остаётся, значение сохраняется, но на экране здесь ничего не изменится.",
  "type.partial": "Ограничение: {caveat}",
  "type.unknown": "Поддержку {css} в этом браузере проверить не удалось.",

  "box.bg": "Фон",
  "box.radius": "Скругление углов",
  "box.pad": "Внутренний отступ",
  "box.border": "Толщина рамки",
  "box.borderColor": "Цвет рамки",
  "box.borderStyle": "Стиль рамки",
  "box.elevation": "Тень уровня",
  "box.opacity": "Непрозрачность",
  "box.solid": "Сплошная",
  "box.dashed": "Штриховая",
  "box.dotted": "Пунктирная",
  "box.double": "Двойная",

  "preset.title": "Сохранённые оформления",
  "preset.name": "Название пресета",
  "preset.namePh": "например Высокий контраст",
  "preset.save": "Сохранить текущее оформление",
  "preset.apply": "Применить: {name}",
  "preset.delete": "Удалить: {name}",
  "preset.export": "Экспорт…",
  "preset.import": "Импорт…",
  "preset.none": "Сохранённых оформлений пока нет.",
  "preset.importedOne": "Импортировано пресетов: {count}.",
  "preset.importFailed": "В этом файле нет пресета оформления, который можно прочитать.",
  "preset.applied": "Применено: {name}.",
  "preset.includes": "Пресет несёт тему, исходный цвет, плотность, типографику и стиль каждого элемента.",

  "rx.open": "Собрать шаблон",
  "rx.title": "Регулярное выражение",
  "rx.mode": "Способ поиска",
  "rx.plain": "Обычный текст",
  "rx.regex": "Регулярка",
  "rx.pattern": "Шаблон",
  "rx.flags": "Флаги",
  "rx.sample": "Пример текста",
  "rx.matches": "совпадений: {count}",
  "rx.noMatches": "Совпадений нет.",
  "rx.truncated": "Показаны только первые совпадения.",
  "rx.groups": "Группы захвата",
  "rx.invalid": "Неверный шаблон: {error}",
  "rx.engine": "JavaScript (ECMAScript) RegExp, выполняется на этой странице. Ничего никуда не отправляется.",
  "rx.insert": "Вставить {token}",
  "rx.apply": "Использовать этот шаблон",
  "rx.close": "Закрыть конструктор шаблонов",
};

const JA: Table = {
  "ap.edit": "外観を編集…",
  "ap.editThis": "この要素の外観を編集",
  "ap.editOf": "{name} の外観を編集",
  "ap.title": "外観 — {name}",
  "ap.close": "外観エディターを閉じる",
  "ap.containers": "親要素",
  "ap.applies": "サイト上のすべての {name} に適用されます。",
  "ap.preview": "プレビュー",
  "ap.previewText": "Aa Bb Cc 0123 — 廣東話 · 한국어 · 日本語 · Русский",
  "ap.secText": "テキスト",
  "ap.secBox": "ボックス",
  "ap.secPresets": "プリセット",
  "ap.reset": "リセット",
  "ap.resetOne": "{name} をリセット",
  "ap.resetElement": "この要素をリセット",
  "ap.resetAll": "すべての要素をリセット",
  "ap.resetAllConfirm": "サイト上のすべての要素の外観をリセットしますか？テーマ・言語・タブには影響しません。",
  "ap.inherits": "継承",
  "ap.none": "なし",
  "ap.default": "既定",
  "ap.customized": "{count} 個の要素をカスタマイズ済み",
  "ap.keyboardHint": "Shift + 右クリックで、どの要素からでもこのエディターを直接開けます。",
  "ap.saved": "保存しました",
  "ap.use": "使う",

  "color.open": "色を選ぶ",
  "color.title": "色",
  "color.field": "彩度と明度",
  "color.fieldHint": "ドラッグするか矢印キーで操作します。Page Up/Down で大きく動きます。",
  "color.hue": "色相",
  "color.chroma": "彩度",
  "color.lightness": "明度",
  "color.alpha": "不透明度",
  "color.value": "値",
  "color.valueHint": "任意の CSS 色：名前、#hex、rgb()、hsl()、lab()、oklch()、device-cmyk()。",
  "color.invalid": "色として読み取れません。直前の値がそのまま適用されています。",
  "color.translator": "各色空間でのこの色",
  "color.copy": "{space} をコピー",
  "color.copied": "コピーしました",
  "color.gamut": "色域",
  "color.clip": "sRGB の外です。oklch() で書き出すため広色域ディスプレイでは正しく表示され、それ以外では最も近い sRGB 色に丸められます。",
  "color.clipFar": "sRGB から大きく外れています。多くの画面ではっきり違う色になります。",
  "color.contrast": "コントラスト",
  "color.contrastAgainst": "{name} との比較",
  "color.contrastSurface": "ページ",
  "color.contrastText": "テキスト",
  "color.eyedropper": "画面から色を取る",
  "color.eyedropperNo": "このブラウザーには画面スポイトがありません。",
  "color.recent": "最近",
  "color.swatches": "テーマの色",
  "color.clear": "色をクリア",
  "color.spectrum": "色相スペクトル",

  "font.family": "書体",
  "font.search": "書体を検索",
  "font.searchPh": "書体を検索",
  "font.installed": "インストール済みフォントを使う",
  "font.installedHint": "この端末の全フォントを列挙する許可をブラウザーに求めます。",
  "font.probed": "計測による一覧",
  "font.local": "インストール済みフォント",
  "font.bundled": "同梱フォントのみ",
  "font.noMatch": "一致する書体がありません。",
  "font.custom": "または書体名を直接入力",
  "font.customPh": "例：Iosevka",
  "font.faces": "{count} 種のフェイス",
  "font.axes": "バリアブル軸",
  "font.axesNone": "この書体にバリアブル軸はありません。",
  "font.axesUnknown": "この書体のバリアブル軸は読み取れませんでした。",
  "font.sample": "Handgloves 廣東話",

  "type.size": "サイズ",
  "type.weight": "ウェイト",
  "type.slant": "スタイル",
  "type.italic": "イタリック",
  "type.oblique": "オブリーク",
  "type.obliqueAngle": "オブリーク角度",
  "type.underline": "下線",
  "type.underlineColor": "下線の色",
  "type.underlineThickness": "下線の太さ",
  "type.strike": "取り消し線",
  "type.strikeSingle": "一重",
  "type.strikeDouble": "二重",
  "type.overline": "上線",
  "type.caps": "大文字小文字",
  "type.upper": "大文字",
  "type.lower": "小文字",
  "type.capitalize": "各単語の先頭を大文字",
  "type.smallCaps": "スモールキャップス",
  "type.allSmallCaps": "全文字スモールキャップス",
  "type.script": "位置",
  "type.super": "上付き",
  "type.sub": "下付き",
  "type.color": "文字色",
  "type.highlight": "ハイライト",
  "type.outline": "袋文字の太さ",
  "type.outlineColor": "袋文字の色",
  "type.shadow": "影",
  "type.shadowX": "影（横）",
  "type.shadowY": "影（縦）",
  "type.shadowBlur": "影のぼかし",
  "type.shadowColor": "影の色",
  "type.glow": "グロー",
  "type.glowColor": "グローの色",
  "type.letterSpacing": "字間",
  "type.wordSpacing": "単語間",
  "type.lineHeight": "行高",
  "type.baseline": "ベースラインの上下",
  "type.direction": "文字方向",
  "type.ltr": "左から右",
  "type.rtl": "右から左",
  "type.align": "揃え",
  "type.alignStart": "先頭",
  "type.alignCenter": "中央",
  "type.alignEnd": "末尾",
  "type.alignJustify": "両端",
  "type.maps": "{css} として描画されます",
  "type.unsupported": "このブラウザーは {css} に対応していません。コントロールは残り値も保持されますが、ここでは見た目が変わりません。",
  "type.partial": "制限：{caveat}",
  "type.unknown": "このブラウザーでは {css} の対応状況を確認できませんでした。",

  "box.bg": "背景",
  "box.radius": "角の丸み",
  "box.pad": "内側の余白",
  "box.border": "枠線の太さ",
  "box.borderColor": "枠線の色",
  "box.borderStyle": "枠線のスタイル",
  "box.elevation": "エレベーション",
  "box.opacity": "不透明度",
  "box.solid": "実線",
  "box.dashed": "破線",
  "box.dotted": "点線",
  "box.double": "二重線",

  "preset.title": "保存した外観",
  "preset.name": "プリセット名",
  "preset.namePh": "例：ハイコントラスト",
  "preset.save": "現在の外観を保存",
  "preset.apply": "{name} を適用",
  "preset.delete": "{name} を削除",
  "preset.export": "書き出し…",
  "preset.import": "読み込み…",
  "preset.none": "保存した外観はまだありません。",
  "preset.importedOne": "{count} 件のプリセットを読み込みました。",
  "preset.importFailed": "このファイルには読み取れる外観プリセットがありません。",
  "preset.applied": "{name} を適用しました。",
  "preset.includes": "プリセットにはテーマ・シード色・密度・タイポグラフィ・要素ごとのスタイルがすべて含まれます。",

  "rx.open": "パターンを組み立てる",
  "rx.title": "正規表現",
  "rx.mode": "照合方法",
  "rx.plain": "プレーンテキスト",
  "rx.regex": "正規表現",
  "rx.pattern": "パターン",
  "rx.flags": "フラグ",
  "rx.sample": "サンプルテキスト",
  "rx.matches": "{count} 件一致",
  "rx.noMatches": "一致なし。",
  "rx.truncated": "先頭の一致のみ表示しています。",
  "rx.groups": "キャプチャグループ",
  "rx.invalid": "無効なパターン：{error}",
  "rx.engine": "このページ内で実行される JavaScript (ECMAScript) の RegExp です。どこにも送信されません。",
  "rx.insert": "{token} を挿入",
  "rx.apply": "このパターンを使う",
  "rx.close": "パターンビルダーを閉じる",
};

const TABLE: Record<StringsLocale, Table> = { root: EN, ko: KO, "zh-cn": ZH, ru: RU, ja: JA };

/**
 * A translator for the appearance surface.
 *
 * The site dictionary is consulted first — both the requested locale and its
 * English base — so once these keys are folded into `strings.ts` the entries
 * here become unreachable and can be deleted in one commit. Until then they are
 * the answer, and every key exists in all five locales because the table type
 * demands it.
 */
export function appearanceT(locale: StringsLocale): TFn {
  const site = stringsFor(locale) as Record<string, string | undefined>;
  const siteBase = stringsFor("root") as Record<string, string | undefined>;
  const own = TABLE[locale] ?? EN;
  return (key, vars) => {
    const value = site[key] ?? siteBase[key]
      ?? (own as Record<string, string | undefined>)[key]
      ?? (EN as Record<string, string | undefined>)[key];
    return fmt(value ?? key.split(".").pop() ?? key, vars);
  };
}
