/**
 * Every string the site's own chrome renders, in the five locales it publishes.
 *
 * `TabStrip` used to carry its own `STRINGS` object with a comment saying a
 * shared dictionary serving one consumer is a layer with nothing in it, and that
 * absorbing it later would be a rename. This is that absorption: the strip, the
 * regex builder, the four tab searches, the site search and the settings search
 * all resolve here, so a locale is complete or it is a type error — not complete
 * in one component and English in the next.
 *
 * Flat, dotted keys rather than nested objects, for one reason: `Strings` is
 * `Record<keyof typeof EN, string>`, so a locale missing a key fails to compile
 * while a locale with different *wording* does not. A nested shape needs a
 * hand-written interface to get the same guarantee, and a hand-written interface
 * is a third place to forget a key.
 *
 * The `regex.*` keys are spelled exactly as the dashboard spells them, because
 * `TOKEN_GROUPS` and `FLAGS` in `shared/m3/regex.ts` carry the dashboard's own
 * key strings on every entry. Matching them means the guided palette translates
 * through this table with no mapping layer, and `t()` falls back to the key's
 * own construct when the dashboard adds a token this table has not caught up
 * with — a chip reading `\p{Script=Han}` with no description is worse than a
 * chip labelled `regex.tokNewThing`, and both are better than a crash.
 *
 * These are the *documentation locales* (the five languages the site publishes),
 * not the language modes of the funny-level rules — English / playful Cantonese /
 * bilingual is a separate axis, owned by the i18n stage, and it layers on top of
 * this table rather than replacing it.
 *
 * What this module deliberately does NOT do: read the DOM, pick a locale for
 * itself, or interpolate anything it was not given. `fmt` substitutes only the
 * placeholders present in the template and leaves an unknown one visible, so a
 * missing variable shows up as `{count}` in review instead of as a plausible
 * sentence with a number silently missing.
 */

/* ------------------------------------------------------------------ model -- */

export const LOCALE_CODES = ["root", "ko", "zh-cn", "ru", "ja"] as const;
export type StringsLocale = (typeof LOCALE_CODES)[number];

const EN = {
  /* ---- tab strip (moved verbatim from TabStrip's own table) -------------- */
  "tabs.tabs": "Tabs",
  "tabs.newTab": "New tab",
  "tabs.close": "Close tab",
  "tabs.more": "More tabs",
  "tabs.pinned": "Pinned",
  "tabs.pin": "Pin tab",
  "tabs.unpin": "Unpin tab",
  "tabs.duplicate": "Duplicate tab",
  "tabs.closeTab": "Close",
  "tabs.closeOthers": "Close other tabs",
  "tabs.closeRight": "Close tabs to the right",
  "tabs.group": "Group",
  "tabs.newGroup": "New group…",
  "tabs.addTo": "Add to group",
  "tabs.removeFrom": "Remove from group",
  "tabs.renameGroup": "Rename group…",
  "tabs.ungroup": "Ungroup",
  "tabs.collapse": "Collapse group",
  "tabs.expand": "Expand group",
  "tabs.groupName": "Group name",
  "tabs.save": "Save",
  "tabs.cancel": "Cancel",
  "tabs.opened": "Opened",
  "tabs.closed": "Closed",

  /* ---- the four tab searches and the two bulk closes --------------------- */
  "tabs.search": "Search tabs",
  "tabs.searchTitle": "Tab search",
  "tabs.searchClose": "Close tab search",
  "tabs.stripSearch": "This tab strip",
  "tabs.stripSearchPh": "Search the tabs in this strip",
  "tabs.groupSearch": "Tab groups",
  "tabs.groupSearchPh": "Search groups by name",
  "tabs.inGroupSearch": "Tabs in {name}",
  "tabs.inGroupSearchPh": "Search this group",
  "tabs.masterSearch": "Every open tab",
  "tabs.masterSearchPh": "Search every tab in every window",
  "tabs.noMatches": "Nothing matches.",
  "tabs.noGroups": "No groups yet.",
  "tabs.resultCount": "{count} of {total}",
  "tabs.thisWindow": "This window",
  "tabs.otherWindow": "Window {n}",
  "tabs.ungrouped": "Ungrouped",
  "tabs.goTo": "Go to this tab",
  "tabs.groupOf": "Group: {name}",
  "tabs.collapsedNote": "in a collapsed group — going there shows the tab without expanding the group",
  "tabs.remote": "in another window — the action happens there",
  "tabs.bulk": "Close tabs in bulk",
  "tabs.bulkContaining": "Close tabs containing text",
  "tabs.bulkNot": "Close tabs NOT containing text",
  "tabs.bulkPh": "Text to match against tab labels",
  "tabs.scope": "Applies to",
  "tabs.scopeStrip": "Every tab in this strip",
  "tabs.scopeUngrouped": "Ungrouped tabs only",
  "tabs.scopeGroup": "Group: {name}",
  "tabs.includePinned": "Include pinned tabs",
  "tabs.pinnedProtected": "{count} pinned tab(s) are protected and will not close.",
  "tabs.pinnedIncluded": "{count} pinned tab(s) WILL be closed.",
  "tabs.previewTitle": "Preview",
  "tabs.wouldClose": "Would close {count} of {total} tab(s):",
  "tabs.wouldCloseNone": "Nothing matches — nothing would close.",
  "tabs.emptyQuery": "Type text to match. An empty query closes nothing.",
  "tabs.invalidQuery": "Invalid pattern: {error}",
  "tabs.modePlain": "Plain text, case-insensitive, matched against the visible tab label only — never page contents.",
  "tabs.modeRegex": "Regular expression /{flags}, matched against the visible tab label only — never page contents.",
  "tabs.doClose": "Close {count} tab(s)",
  "tabs.neverEmpty": "One tab always survives: the strip is never left empty.",
  "tabs.closedN": "Closed {count} tab(s)",

  /* ---- the site's own content search ------------------------------------- */
  "search.label": "Search",
  "search.open": "Search the documentation",
  "search.ph": "Search the documentation",
  "search.close": "Close search",
  "search.modeLabel": "Match with",
  "search.plainMode": "Plain text",
  "search.regexMode": "Regex",
  "search.results": "{count} result(s)",
  "search.none": "Nothing matches.",
  "search.loading": "Searching…",
  "search.indexing": "Loading this language's page index…",
  "search.engine": "Plain text searches this site's Pagefind index. Regex is evaluated locally over a page index loaded into this browser.",
  "search.indexFailed": "The page index could not be loaded, so regex search is unavailable on this page.",
  "search.pagefindFailed": "Pagefind is unavailable in this build, so plain text is searching the local page index instead.",
  "search.clear": "Clear the query",
  "search.hint": "Press / to search",
  "search.matchesOnPage": "{count} match(es)",
  "search.moreResults": "Showing the first {count}. Narrow the query to see the rest.",

  /* ---- the settings search ----------------------------------------------- */
  "settings.search": "Search settings",
  "settings.searchPh": "Search by name, description or current value",
  "settings.shown": "{shown} of {total} setting(s)",
  "settings.none": "No setting matches.",
  "toc.search": "Search this page's headings",
  "toc.searchPh": "Filter the headings on this page",
  "toc.none": "No heading matches.",
  "toc.shown": "{shown} of {total} heading(s)",
  "settings.elsewhere": "{count} more on another tab: {tabs}",
  "settings.clear": "Clear the query",

  /* ---- the regex builder (keys spelled as the dashboard spells them) ------ */
  "regex.open": "Open the regex builder",
  "regex.title": "Regex builder",
  "regex.close": "Close the regex builder",
  "regex.engineNote": "Engine: ECMAScript RegExp, evaluated locally in this browser. Nothing you type is sent anywhere.",
  "regex.pattern": "Pattern",
  "regex.patternCap": "{used} of {cap} characters",
  "regex.flags": "Flags",
  "regex.invalid": "Invalid pattern",
  "regex.build": "Guided construction",
  "regex.palette": "Token palette",
  "regex.sample": "Sample text",
  "regex.sampleCap": "{used} of {cap} characters",
  "regex.sampleSeeded": "Seeded from what this search can actually see, so a match here is a match there.",
  "regex.matches": "Matches",
  "regex.matchCountValue": "{count} match(es)",
  "regex.matchTruncated": "Stopped at the {cap}-match cap — refine the pattern to see the rest.",
  "regex.noMatches": "No matches in the sample text.",
  "regex.groups": "Capture groups",
  "regex.noGroups": "This pattern declares no named capture group.",
  "regex.safety": "Evaluated locally, never transmitted. Pattern capped at {pattern} characters, sample at {sample}, matches at {matches}, with zero-width advance so a catastrophic pattern cannot hang the page.",
  "regex.apply": "Apply",
  "regex.applyHint": "Applying puts this pattern in the field and switches it to regex.",
  "regex.applyHintPlain": "Applying puts this pattern in the field.",
  "regex.flagG": "global — find every match, not just the first",
  "regex.flagI": "ignore case",
  "regex.flagM": "multiline — ^ and $ match line boundaries",
  "regex.flagS": "dotall — . also matches a newline",
  "regex.flagU": "unicode",
  "regex.flagY": "sticky — match only at lastIndex",
  "regex.groupLiterals": "Literals",
  "regex.groupClasses": "Character classes",
  "regex.groupAnchors": "Anchors",
  "regex.groupGroups": "Groups",
  "regex.groupAlternation": "Alternation",
  "regex.groupQuantifiers": "Quantifiers",
  "regex.tokLiteral": "literal text",
  "regex.tokEscapedDot": "escaped dot — a literal .",
  "regex.tokBackslash": "a literal backslash",
  "regex.tokDigit": "any digit",
  "regex.tokWord": "any word character",
  "regex.tokSpace": "any whitespace",
  "regex.tokAny": "any character",
  "regex.tokClass": "character class",
  "regex.tokNegated": "any character except /",
  "regex.tokUnicodeScript": "Unicode script — needs the u flag",
  "regex.tokStart": "start of input",
  "regex.tokEnd": "end of input",
  "regex.tokBoundary": "word boundary",
  "regex.tokCapture": "capture group",
  "regex.tokNamed": "named capture group",
  "regex.tokGroup": "non-capturing group",
  "regex.tokLookahead": "lookahead",
  "regex.tokAlt": "either side",
  "regex.tokStar": "zero or more",
  "regex.tokPlus": "one or more",
  "regex.tokOpt": "optional",
  "regex.tokRange": "between 1 and 3 times",
  "regex.tokLazy": "one or more, lazy",
};

/** Every key the English table declares. A locale short of one will not compile. */
export type StringKey = keyof typeof EN;
export type Strings = Record<StringKey, string>;

const KO: Strings = {
  "tabs.tabs": "탭",
  "tabs.newTab": "새 탭",
  "tabs.close": "탭 닫기",
  "tabs.more": "더 많은 탭",
  "tabs.pinned": "고정됨",
  "tabs.pin": "탭 고정",
  "tabs.unpin": "고정 해제",
  "tabs.duplicate": "탭 복제",
  "tabs.closeTab": "닫기",
  "tabs.closeOthers": "다른 탭 닫기",
  "tabs.closeRight": "오른쪽 탭 닫기",
  "tabs.group": "그룹",
  "tabs.newGroup": "새 그룹…",
  "tabs.addTo": "그룹에 추가",
  "tabs.removeFrom": "그룹에서 제거",
  "tabs.renameGroup": "그룹 이름 변경…",
  "tabs.ungroup": "그룹 해제",
  "tabs.collapse": "그룹 접기",
  "tabs.expand": "그룹 펼치기",
  "tabs.groupName": "그룹 이름",
  "tabs.save": "저장",
  "tabs.cancel": "취소",
  "tabs.opened": "열림",
  "tabs.closed": "닫힘",

  "tabs.search": "탭 검색",
  "tabs.searchTitle": "탭 검색",
  "tabs.searchClose": "탭 검색 닫기",
  "tabs.stripSearch": "이 탭 목록",
  "tabs.stripSearchPh": "이 목록의 탭 검색",
  "tabs.groupSearch": "탭 그룹",
  "tabs.groupSearchPh": "이름으로 그룹 검색",
  "tabs.inGroupSearch": "{name} 그룹의 탭",
  "tabs.inGroupSearchPh": "이 그룹에서 검색",
  "tabs.masterSearch": "열려 있는 모든 탭",
  "tabs.masterSearchPh": "모든 창의 모든 탭 검색",
  "tabs.noMatches": "일치하는 항목이 없습니다.",
  "tabs.noGroups": "아직 그룹이 없습니다.",
  "tabs.resultCount": "{total}개 중 {count}개",
  "tabs.thisWindow": "현재 창",
  "tabs.otherWindow": "창 {n}",
  "tabs.ungrouped": "그룹 없음",
  "tabs.goTo": "이 탭으로 이동",
  "tabs.groupOf": "그룹: {name}",
  "tabs.collapsedNote": "접힌 그룹에 있음 — 이동해도 그룹은 펼쳐지지 않습니다",
  "tabs.remote": "다른 창에 있음 — 해당 창에서 실행됩니다",
  "tabs.bulk": "탭 일괄 닫기",
  "tabs.bulkContaining": "텍스트를 포함하는 탭 닫기",
  "tabs.bulkNot": "텍스트를 포함하지 않는 탭 닫기",
  "tabs.bulkPh": "탭 이름과 대조할 텍스트",
  "tabs.scope": "적용 범위",
  "tabs.scopeStrip": "이 목록의 모든 탭",
  "tabs.scopeUngrouped": "그룹 없는 탭만",
  "tabs.scopeGroup": "그룹: {name}",
  "tabs.includePinned": "고정된 탭 포함",
  "tabs.pinnedProtected": "고정된 탭 {count}개는 보호되어 닫히지 않습니다.",
  "tabs.pinnedIncluded": "고정된 탭 {count}개도 닫힙니다.",
  "tabs.previewTitle": "미리 보기",
  "tabs.wouldClose": "탭 {total}개 중 {count}개를 닫습니다:",
  "tabs.wouldCloseNone": "일치하는 항목이 없어 아무것도 닫지 않습니다.",
  "tabs.emptyQuery": "대조할 텍스트를 입력하세요. 빈 검색어는 아무것도 닫지 않습니다.",
  "tabs.invalidQuery": "잘못된 패턴: {error}",
  "tabs.modePlain": "일반 텍스트, 대소문자 무시. 페이지 내용이 아니라 화면에 보이는 탭 이름만 대조합니다.",
  "tabs.modeRegex": "정규식 /{flags}. 페이지 내용이 아니라 화면에 보이는 탭 이름만 대조합니다.",
  "tabs.doClose": "탭 {count}개 닫기",
  "tabs.neverEmpty": "탭 하나는 항상 남습니다. 목록이 비는 일은 없습니다.",
  "tabs.closedN": "탭 {count}개를 닫았습니다",

  "search.label": "검색",
  "search.open": "문서 검색",
  "search.ph": "문서 검색",
  "search.close": "검색 닫기",
  "search.modeLabel": "검색 방식",
  "search.plainMode": "일반 텍스트",
  "search.regexMode": "정규식",
  "search.results": "결과 {count}개",
  "search.none": "일치하는 항목이 없습니다.",
  "search.loading": "검색 중…",
  "search.indexing": "이 언어의 페이지 색인을 불러오는 중…",
  "search.engine": "일반 텍스트는 이 사이트의 Pagefind 색인을 사용합니다. 정규식은 브라우저에 불러온 페이지 색인에서 로컬로 평가됩니다.",
  "search.indexFailed": "페이지 색인을 불러오지 못해 이 페이지에서는 정규식 검색을 사용할 수 없습니다.",
  "search.pagefindFailed": "이 빌드에서는 Pagefind를 사용할 수 없어 일반 텍스트도 로컬 페이지 색인에서 검색합니다.",
  "search.clear": "검색어 지우기",
  "search.hint": "/ 를 눌러 검색",
  "search.matchesOnPage": "일치 {count}개",
  "search.moreResults": "처음 {count}개만 표시합니다. 검색어를 좁혀 나머지를 확인하세요.",

  "settings.search": "설정 검색",
  "settings.searchPh": "이름, 설명 또는 현재 값으로 검색",
  "settings.shown": "설정 {total}개 중 {shown}개",
  "settings.none": "일치하는 설정이 없습니다.",
  "toc.search": "이 페이지의 제목 검색",
  "toc.searchPh": "이 페이지의 제목 필터링",
  "toc.none": "일치하는 제목이 없습니다.",
  "toc.shown": "제목 {total}개 중 {shown}개",
  "settings.elsewhere": "다른 탭에 {count}개 더 있습니다: {tabs}",
  "settings.clear": "검색어 지우기",

  "regex.open": "정규식 빌더 열기",
  "regex.title": "정규식 빌더",
  "regex.close": "정규식 빌더 닫기",
  "regex.engineNote": "엔진: ECMAScript RegExp, 이 브라우저에서 로컬로 평가됩니다. 입력한 내용은 어디에도 전송되지 않습니다.",
  "regex.pattern": "패턴",
  "regex.patternCap": "{cap}자 중 {used}자",
  "regex.flags": "플래그",
  "regex.invalid": "잘못된 패턴",
  "regex.build": "가이드 구성",
  "regex.palette": "토큰 팔레트",
  "regex.sample": "샘플 텍스트",
  "regex.sampleCap": "{cap}자 중 {used}자",
  "regex.sampleSeeded": "이 검색이 실제로 볼 수 있는 내용으로 채워집니다. 여기서 일치하면 저기서도 일치합니다.",
  "regex.matches": "일치",
  "regex.matchCountValue": "{count}개 일치",
  "regex.matchTruncated": "{cap}개 상한에서 중단했습니다 — 패턴을 좁혀 나머지를 확인하세요.",
  "regex.noMatches": "샘플 텍스트에 일치하는 항목이 없습니다.",
  "regex.groups": "캡처 그룹",
  "regex.noGroups": "이 패턴에는 이름 있는 캡처 그룹이 없습니다.",
  "regex.safety": "로컬에서만 평가되며 전송되지 않습니다. 패턴 {pattern}자, 샘플 {sample}자, 일치 {matches}개로 제한되고 폭 0 일치는 강제로 전진하므로 치명적인 패턴이 페이지를 멈출 수 없습니다.",
  "regex.apply": "적용",
  "regex.applyHint": "적용하면 이 패턴이 입력란에 들어가고 정규식 모드로 전환됩니다.",
  "regex.applyHintPlain": "적용하면 이 패턴이 입력란에 들어갑니다.",
  "regex.flagG": "global — 첫 번째뿐 아니라 모든 일치를 찾습니다",
  "regex.flagI": "대소문자 무시",
  "regex.flagM": "multiline — ^ 와 $ 가 줄 경계와 일치합니다",
  "regex.flagS": "dotall — . 이 줄바꿈에도 일치합니다",
  "regex.flagU": "유니코드",
  "regex.flagY": "sticky — lastIndex 에서만 일치합니다",
  "regex.groupLiterals": "리터럴",
  "regex.groupClasses": "문자 클래스",
  "regex.groupAnchors": "앵커",
  "regex.groupGroups": "그룹",
  "regex.groupAlternation": "선택",
  "regex.groupQuantifiers": "수량자",
  "regex.tokLiteral": "리터럴 텍스트",
  "regex.tokEscapedDot": "이스케이프된 점 — 리터럴 .",
  "regex.tokBackslash": "리터럴 역슬래시",
  "regex.tokDigit": "임의의 숫자",
  "regex.tokWord": "임의의 단어 문자",
  "regex.tokSpace": "임의의 공백",
  "regex.tokAny": "임의의 문자",
  "regex.tokClass": "문자 클래스",
  "regex.tokNegated": "/ 를 제외한 모든 문자",
  "regex.tokUnicodeScript": "유니코드 스크립트 — u 플래그 필요",
  "regex.tokStart": "입력의 시작",
  "regex.tokEnd": "입력의 끝",
  "regex.tokBoundary": "단어 경계",
  "regex.tokCapture": "캡처 그룹",
  "regex.tokNamed": "이름 있는 캡처 그룹",
  "regex.tokGroup": "캡처하지 않는 그룹",
  "regex.tokLookahead": "전방 탐색",
  "regex.tokAlt": "둘 중 하나",
  "regex.tokStar": "0회 이상",
  "regex.tokPlus": "1회 이상",
  "regex.tokOpt": "선택 사항",
  "regex.tokRange": "1회에서 3회",
  "regex.tokLazy": "1회 이상, 게으르게",
};

const ZH: Strings = {
  "tabs.tabs": "标签页",
  "tabs.newTab": "新建标签页",
  "tabs.close": "关闭标签页",
  "tabs.more": "更多标签页",
  "tabs.pinned": "已固定",
  "tabs.pin": "固定标签页",
  "tabs.unpin": "取消固定",
  "tabs.duplicate": "复制标签页",
  "tabs.closeTab": "关闭",
  "tabs.closeOthers": "关闭其他标签页",
  "tabs.closeRight": "关闭右侧标签页",
  "tabs.group": "分组",
  "tabs.newGroup": "新建分组…",
  "tabs.addTo": "加入分组",
  "tabs.removeFrom": "移出分组",
  "tabs.renameGroup": "重命名分组…",
  "tabs.ungroup": "解散分组",
  "tabs.collapse": "折叠分组",
  "tabs.expand": "展开分组",
  "tabs.groupName": "分组名称",
  "tabs.save": "保存",
  "tabs.cancel": "取消",
  "tabs.opened": "已打开",
  "tabs.closed": "已关闭",

  "tabs.search": "搜索标签页",
  "tabs.searchTitle": "标签页搜索",
  "tabs.searchClose": "关闭标签页搜索",
  "tabs.stripSearch": "当前标签栏",
  "tabs.stripSearchPh": "搜索本标签栏中的标签页",
  "tabs.groupSearch": "标签分组",
  "tabs.groupSearchPh": "按名称搜索分组",
  "tabs.inGroupSearch": "{name} 中的标签页",
  "tabs.inGroupSearchPh": "在该分组中搜索",
  "tabs.masterSearch": "所有打开的标签页",
  "tabs.masterSearchPh": "搜索所有窗口中的每个标签页",
  "tabs.noMatches": "没有匹配项。",
  "tabs.noGroups": "还没有分组。",
  "tabs.resultCount": "{total} 项中的 {count} 项",
  "tabs.thisWindow": "当前窗口",
  "tabs.otherWindow": "窗口 {n}",
  "tabs.ungrouped": "未分组",
  "tabs.goTo": "前往该标签页",
  "tabs.groupOf": "分组：{name}",
  "tabs.collapsedNote": "位于已折叠的分组中 — 前往它不会展开该分组",
  "tabs.remote": "位于另一个窗口 — 操作将在那里执行",
  "tabs.bulk": "批量关闭标签页",
  "tabs.bulkContaining": "关闭包含文本的标签页",
  "tabs.bulkNot": "关闭不包含文本的标签页",
  "tabs.bulkPh": "用于匹配标签名称的文本",
  "tabs.scope": "作用范围",
  "tabs.scopeStrip": "本标签栏的全部标签页",
  "tabs.scopeUngrouped": "仅未分组的标签页",
  "tabs.scopeGroup": "分组：{name}",
  "tabs.includePinned": "包含已固定的标签页",
  "tabs.pinnedProtected": "{count} 个已固定的标签页受保护，不会被关闭。",
  "tabs.pinnedIncluded": "{count} 个已固定的标签页也会被关闭。",
  "tabs.previewTitle": "预览",
  "tabs.wouldClose": "将关闭 {total} 个标签页中的 {count} 个：",
  "tabs.wouldCloseNone": "没有匹配项 — 不会关闭任何标签页。",
  "tabs.emptyQuery": "请输入要匹配的文本。空查询不会关闭任何标签页。",
  "tabs.invalidQuery": "无效的模式：{error}",
  "tabs.modePlain": "纯文本，忽略大小写，只匹配可见的标签名称，绝不读取页面内容。",
  "tabs.modeRegex": "正则表达式 /{flags}，只匹配可见的标签名称，绝不读取页面内容。",
  "tabs.doClose": "关闭 {count} 个标签页",
  "tabs.neverEmpty": "始终保留一个标签页：标签栏不会变空。",
  "tabs.closedN": "已关闭 {count} 个标签页",

  "search.label": "搜索",
  "search.open": "搜索文档",
  "search.ph": "搜索文档",
  "search.close": "关闭搜索",
  "search.modeLabel": "匹配方式",
  "search.plainMode": "纯文本",
  "search.regexMode": "正则",
  "search.results": "{count} 条结果",
  "search.none": "没有匹配项。",
  "search.loading": "搜索中…",
  "search.indexing": "正在加载该语言的页面索引…",
  "search.engine": "纯文本使用本站的 Pagefind 索引；正则在浏览器本地对已加载的页面索引求值。",
  "search.indexFailed": "页面索引加载失败，本页无法使用正则搜索。",
  "search.pagefindFailed": "此构建中没有 Pagefind，纯文本改为在本地页面索引中搜索。",
  "search.clear": "清除查询",
  "search.hint": "按 / 搜索",
  "search.matchesOnPage": "{count} 处匹配",
  "search.moreResults": "仅显示前 {count} 条。缩小查询范围以查看其余结果。",

  "settings.search": "搜索设置",
  "settings.searchPh": "按名称、说明或当前值搜索",
  "settings.shown": "{total} 项设置中的 {shown} 项",
  "settings.none": "没有匹配的设置。",
  "toc.search": "搜索本页标题",
  "toc.searchPh": "筛选本页标题",
  "toc.none": "没有匹配的标题。",
  "toc.shown": "{total} 个标题中显示 {shown} 个",
  "settings.elsewhere": "另一个标签页中还有 {count} 项：{tabs}",
  "settings.clear": "清除查询",

  "regex.open": "打开正则构建器",
  "regex.title": "正则构建器",
  "regex.close": "关闭正则构建器",
  "regex.engineNote": "引擎：ECMAScript RegExp，在本浏览器中本地求值。你输入的内容不会发送到任何地方。",
  "regex.pattern": "模式",
  "regex.patternCap": "{cap} 个字符中的 {used} 个",
  "regex.flags": "标志",
  "regex.invalid": "无效的模式",
  "regex.build": "引导式构建",
  "regex.palette": "标记面板",
  "regex.sample": "示例文本",
  "regex.sampleCap": "{cap} 个字符中的 {used} 个",
  "regex.sampleSeeded": "取自该搜索实际能看到的内容，所以这里匹配上了，那里也会匹配上。",
  "regex.matches": "匹配",
  "regex.matchCountValue": "{count} 处匹配",
  "regex.matchTruncated": "已在 {cap} 处匹配上限停止 — 请细化模式以查看其余部分。",
  "regex.noMatches": "示例文本中没有匹配项。",
  "regex.groups": "捕获组",
  "regex.noGroups": "该模式没有声明具名捕获组。",
  "regex.safety": "仅在本地求值，绝不传输。模式上限 {pattern} 个字符，示例上限 {sample} 个字符，匹配上限 {matches} 处，并对零宽匹配强制前进，因此灾难性模式无法卡住页面。",
  "regex.apply": "应用",
  "regex.applyHint": "应用会把该模式填入输入框并切换为正则模式。",
  "regex.applyHintPlain": "应用会把该模式填入输入框。",
  "regex.flagG": "global — 查找每一处匹配，而不只是第一处",
  "regex.flagI": "忽略大小写",
  "regex.flagM": "multiline — ^ 与 $ 匹配行边界",
  "regex.flagS": "dotall — . 也匹配换行",
  "regex.flagU": "Unicode",
  "regex.flagY": "sticky — 只在 lastIndex 处匹配",
  "regex.groupLiterals": "字面量",
  "regex.groupClasses": "字符类",
  "regex.groupAnchors": "锚点",
  "regex.groupGroups": "分组",
  "regex.groupAlternation": "或",
  "regex.groupQuantifiers": "量词",
  "regex.tokLiteral": "字面文本",
  "regex.tokEscapedDot": "转义的点 — 字面的 .",
  "regex.tokBackslash": "字面的反斜杠",
  "regex.tokDigit": "任意数字",
  "regex.tokWord": "任意单词字符",
  "regex.tokSpace": "任意空白",
  "regex.tokAny": "任意字符",
  "regex.tokClass": "字符类",
  "regex.tokNegated": "除 / 以外的任意字符",
  "regex.tokUnicodeScript": "Unicode 文字 — 需要 u 标志",
  "regex.tokStart": "输入的开头",
  "regex.tokEnd": "输入的结尾",
  "regex.tokBoundary": "单词边界",
  "regex.tokCapture": "捕获组",
  "regex.tokNamed": "具名捕获组",
  "regex.tokGroup": "非捕获组",
  "regex.tokLookahead": "先行断言",
  "regex.tokAlt": "任选其一",
  "regex.tokStar": "零次或多次",
  "regex.tokPlus": "一次或多次",
  "regex.tokOpt": "可选",
  "regex.tokRange": "一到三次",
  "regex.tokLazy": "一次或多次，惰性",
};

const RU: Strings = {
  "tabs.tabs": "Вкладки",
  "tabs.newTab": "Новая вкладка",
  "tabs.close": "Закрыть вкладку",
  "tabs.more": "Ещё вкладки",
  "tabs.pinned": "Закреплённые",
  "tabs.pin": "Закрепить",
  "tabs.unpin": "Открепить",
  "tabs.duplicate": "Дублировать",
  "tabs.closeTab": "Закрыть",
  "tabs.closeOthers": "Закрыть другие вкладки",
  "tabs.closeRight": "Закрыть вкладки справа",
  "tabs.group": "Группа",
  "tabs.newGroup": "Новая группа…",
  "tabs.addTo": "Добавить в группу",
  "tabs.removeFrom": "Убрать из группы",
  "tabs.renameGroup": "Переименовать группу…",
  "tabs.ungroup": "Разгруппировать",
  "tabs.collapse": "Свернуть группу",
  "tabs.expand": "Развернуть группу",
  "tabs.groupName": "Название группы",
  "tabs.save": "Сохранить",
  "tabs.cancel": "Отмена",
  "tabs.opened": "Открыто",
  "tabs.closed": "Закрыто",

  "tabs.search": "Поиск по вкладкам",
  "tabs.searchTitle": "Поиск вкладок",
  "tabs.searchClose": "Закрыть поиск вкладок",
  "tabs.stripSearch": "Эта панель вкладок",
  "tabs.stripSearchPh": "Искать среди вкладок этой панели",
  "tabs.groupSearch": "Группы вкладок",
  "tabs.groupSearchPh": "Искать группы по названию",
  "tabs.inGroupSearch": "Вкладки в «{name}»",
  "tabs.inGroupSearchPh": "Искать в этой группе",
  "tabs.masterSearch": "Все открытые вкладки",
  "tabs.masterSearchPh": "Искать по всем вкладкам во всех окнах",
  "tabs.noMatches": "Совпадений нет.",
  "tabs.noGroups": "Групп пока нет.",
  "tabs.resultCount": "{count} из {total}",
  "tabs.thisWindow": "Это окно",
  "tabs.otherWindow": "Окно {n}",
  "tabs.ungrouped": "Без группы",
  "tabs.goTo": "Перейти к вкладке",
  "tabs.groupOf": "Группа: {name}",
  "tabs.collapsedNote": "в свёрнутой группе — переход покажет вкладку, не разворачивая группу",
  "tabs.remote": "в другом окне — действие произойдёт там",
  "tabs.bulk": "Массовое закрытие вкладок",
  "tabs.bulkContaining": "Закрыть вкладки, содержащие текст",
  "tabs.bulkNot": "Закрыть вкладки, НЕ содержащие текст",
  "tabs.bulkPh": "Текст для сравнения с названиями вкладок",
  "tabs.scope": "Применяется к",
  "tabs.scopeStrip": "Все вкладки этой панели",
  "tabs.scopeUngrouped": "Только вкладки без группы",
  "tabs.scopeGroup": "Группа: {name}",
  "tabs.includePinned": "Включить закреплённые вкладки",
  "tabs.pinnedProtected": "Закреплённых вкладок под защитой: {count}. Они не закроются.",
  "tabs.pinnedIncluded": "Закреплённые вкладки ({count}) БУДУТ закрыты.",
  "tabs.previewTitle": "Предпросмотр",
  "tabs.wouldClose": "Будет закрыто {count} из {total}:",
  "tabs.wouldCloseNone": "Совпадений нет — ничего не закроется.",
  "tabs.emptyQuery": "Введите текст для сравнения. Пустой запрос ничего не закрывает.",
  "tabs.invalidQuery": "Недопустимый шаблон: {error}",
  "tabs.modePlain": "Обычный текст, без учёта регистра; сравнивается только с видимым названием вкладки, но не с содержимым страницы.",
  "tabs.modeRegex": "Регулярное выражение /{flags}; сравнивается только с видимым названием вкладки, но не с содержимым страницы.",
  "tabs.doClose": "Закрыть вкладок: {count}",
  "tabs.neverEmpty": "Одна вкладка остаётся всегда: панель не бывает пустой.",
  "tabs.closedN": "Закрыто вкладок: {count}",

  "search.label": "Поиск",
  "search.open": "Искать в документации",
  "search.ph": "Искать в документации",
  "search.close": "Закрыть поиск",
  "search.modeLabel": "Способ поиска",
  "search.plainMode": "Обычный текст",
  "search.regexMode": "Регулярка",
  "search.results": "Результатов: {count}",
  "search.none": "Совпадений нет.",
  "search.loading": "Идёт поиск…",
  "search.indexing": "Загружается индекс страниц для этого языка…",
  "search.engine": "Обычный текст ищет по индексу Pagefind этого сайта. Регулярное выражение выполняется локально по индексу страниц, загруженному в браузер.",
  "search.indexFailed": "Индекс страниц не загрузился, поэтому поиск по регулярному выражению недоступен на этой странице.",
  "search.pagefindFailed": "В этой сборке нет Pagefind, поэтому обычный текст ищется по локальному индексу страниц.",
  "search.clear": "Очистить запрос",
  "search.hint": "Нажмите /, чтобы искать",
  "search.matchesOnPage": "Совпадений: {count}",
  "search.moreResults": "Показаны первые {count}. Уточните запрос, чтобы увидеть остальные.",

  "settings.search": "Поиск по настройкам",
  "settings.searchPh": "Искать по названию, описанию или текущему значению",
  "settings.shown": "{shown} из {total} настроек",
  "settings.none": "Подходящих настроек нет.",
  "toc.search": "Поиск по заголовкам страницы",
  "toc.searchPh": "Фильтр заголовков этой страницы",
  "toc.none": "Подходящих заголовков нет.",
  "toc.shown": "{shown} из {total} заголовк(ов)",
  "settings.elsewhere": "Ещё {count} на другой вкладке: {tabs}",
  "settings.clear": "Очистить запрос",

  "regex.open": "Открыть конструктор регулярных выражений",
  "regex.title": "Конструктор регулярных выражений",
  "regex.close": "Закрыть конструктор",
  "regex.engineNote": "Движок: ECMAScript RegExp, вычисляется локально в этом браузере. Ничего из введённого никуда не отправляется.",
  "regex.pattern": "Шаблон",
  "regex.patternCap": "{used} из {cap} символов",
  "regex.flags": "Флаги",
  "regex.invalid": "Недопустимый шаблон",
  "regex.build": "Пошаговое построение",
  "regex.palette": "Палитра конструкций",
  "regex.sample": "Пример текста",
  "regex.sampleCap": "{used} из {cap} символов",
  "regex.sampleSeeded": "Заполнено тем, что этот поиск действительно видит, — совпало здесь, совпадёт и там.",
  "regex.matches": "Совпадения",
  "regex.matchCountValue": "Совпадений: {count}",
  "regex.matchTruncated": "Остановлено на пределе в {cap} совпадений — уточните шаблон, чтобы увидеть остальные.",
  "regex.noMatches": "В примере текста совпадений нет.",
  "regex.groups": "Группы захвата",
  "regex.noGroups": "В этом шаблоне нет именованных групп захвата.",
  "regex.safety": "Вычисляется локально и никуда не передаётся. Шаблон ограничен {pattern} символами, пример — {sample}, совпадения — {matches}, а нулевая ширина принудительно сдвигается, поэтому катастрофический шаблон не подвесит страницу.",
  "regex.apply": "Применить",
  "regex.applyHint": "Применение подставит шаблон в поле и переключит его на регулярное выражение.",
  "regex.applyHintPlain": "Применение подставит шаблон в поле.",
  "regex.flagG": "global — находить все совпадения, а не только первое",
  "regex.flagI": "без учёта регистра",
  "regex.flagM": "multiline — ^ и $ совпадают с границами строк",
  "regex.flagS": "dotall — точка совпадает и с переводом строки",
  "regex.flagU": "Юникод",
  "regex.flagY": "sticky — совпадение только на позиции lastIndex",
  "regex.groupLiterals": "Литералы",
  "regex.groupClasses": "Классы символов",
  "regex.groupAnchors": "Якоря",
  "regex.groupGroups": "Группы",
  "regex.groupAlternation": "Выбор",
  "regex.groupQuantifiers": "Квантификаторы",
  "regex.tokLiteral": "буквальный текст",
  "regex.tokEscapedDot": "экранированная точка — буквальная .",
  "regex.tokBackslash": "буквальная обратная косая черта",
  "regex.tokDigit": "любая цифра",
  "regex.tokWord": "любой словесный символ",
  "regex.tokSpace": "любой пробельный символ",
  "regex.tokAny": "любой символ",
  "regex.tokClass": "класс символов",
  "regex.tokNegated": "любой символ, кроме /",
  "regex.tokUnicodeScript": "письменность Юникода — нужен флаг u",
  "regex.tokStart": "начало ввода",
  "regex.tokEnd": "конец ввода",
  "regex.tokBoundary": "граница слова",
  "regex.tokCapture": "группа захвата",
  "regex.tokNamed": "именованная группа захвата",
  "regex.tokGroup": "группа без захвата",
  "regex.tokLookahead": "опережающая проверка",
  "regex.tokAlt": "любая из сторон",
  "regex.tokStar": "ноль или больше",
  "regex.tokPlus": "один или больше",
  "regex.tokOpt": "необязательно",
  "regex.tokRange": "от одного до трёх раз",
  "regex.tokLazy": "один или больше, лениво",
};

const JA: Strings = {
  "tabs.tabs": "タブ",
  "tabs.newTab": "新しいタブ",
  "tabs.close": "タブを閉じる",
  "tabs.more": "他のタブ",
  "tabs.pinned": "固定済み",
  "tabs.pin": "タブを固定",
  "tabs.unpin": "固定を解除",
  "tabs.duplicate": "タブを複製",
  "tabs.closeTab": "閉じる",
  "tabs.closeOthers": "他のタブを閉じる",
  "tabs.closeRight": "右側のタブを閉じる",
  "tabs.group": "グループ",
  "tabs.newGroup": "新しいグループ…",
  "tabs.addTo": "グループに追加",
  "tabs.removeFrom": "グループから外す",
  "tabs.renameGroup": "グループ名を変更…",
  "tabs.ungroup": "グループを解除",
  "tabs.collapse": "グループを折りたたむ",
  "tabs.expand": "グループを展開",
  "tabs.groupName": "グループ名",
  "tabs.save": "保存",
  "tabs.cancel": "キャンセル",
  "tabs.opened": "開きました",
  "tabs.closed": "閉じました",

  "tabs.search": "タブを検索",
  "tabs.searchTitle": "タブ検索",
  "tabs.searchClose": "タブ検索を閉じる",
  "tabs.stripSearch": "このタブバー",
  "tabs.stripSearchPh": "このバーのタブを検索",
  "tabs.groupSearch": "タブグループ",
  "tabs.groupSearchPh": "名前でグループを検索",
  "tabs.inGroupSearch": "{name} のタブ",
  "tabs.inGroupSearchPh": "このグループ内を検索",
  "tabs.masterSearch": "開いているすべてのタブ",
  "tabs.masterSearchPh": "すべてのウィンドウのタブを検索",
  "tabs.noMatches": "一致するものはありません。",
  "tabs.noGroups": "グループはまだありません。",
  "tabs.resultCount": "{total} 件中 {count} 件",
  "tabs.thisWindow": "このウィンドウ",
  "tabs.otherWindow": "ウィンドウ {n}",
  "tabs.ungrouped": "グループなし",
  "tabs.goTo": "このタブへ移動",
  "tabs.groupOf": "グループ: {name}",
  "tabs.collapsedNote": "折りたたまれたグループ内 — 移動してもグループは展開されません",
  "tabs.remote": "別のウィンドウ — 操作はそちらで実行されます",
  "tabs.bulk": "タブの一括クローズ",
  "tabs.bulkContaining": "テキストを含むタブを閉じる",
  "tabs.bulkNot": "テキストを含まないタブを閉じる",
  "tabs.bulkPh": "タブ名と照合するテキスト",
  "tabs.scope": "適用範囲",
  "tabs.scopeStrip": "このバーのすべてのタブ",
  "tabs.scopeUngrouped": "グループなしのタブのみ",
  "tabs.scopeGroup": "グループ: {name}",
  "tabs.includePinned": "固定タブも含める",
  "tabs.pinnedProtected": "固定タブ {count} 件は保護され、閉じられません。",
  "tabs.pinnedIncluded": "固定タブ {count} 件も閉じられます。",
  "tabs.previewTitle": "プレビュー",
  "tabs.wouldClose": "{total} 件中 {count} 件を閉じます:",
  "tabs.wouldCloseNone": "一致なし — 何も閉じられません。",
  "tabs.emptyQuery": "照合するテキストを入力してください。空の検索語では何も閉じません。",
  "tabs.invalidQuery": "無効なパターン: {error}",
  "tabs.modePlain": "プレーンテキスト、大文字小文字を区別せず、ページ内容ではなく表示中のタブ名だけを照合します。",
  "tabs.modeRegex": "正規表現 /{flags}。ページ内容ではなく表示中のタブ名だけを照合します。",
  "tabs.doClose": "{count} 件のタブを閉じる",
  "tabs.neverEmpty": "タブは必ず 1 つ残ります。バーが空になることはありません。",
  "tabs.closedN": "{count} 件のタブを閉じました",

  "search.label": "検索",
  "search.open": "ドキュメントを検索",
  "search.ph": "ドキュメントを検索",
  "search.close": "検索を閉じる",
  "search.modeLabel": "照合方法",
  "search.plainMode": "プレーンテキスト",
  "search.regexMode": "正規表現",
  "search.results": "{count} 件の結果",
  "search.none": "一致するものはありません。",
  "search.loading": "検索中…",
  "search.indexing": "この言語のページインデックスを読み込み中…",
  "search.engine": "プレーンテキストはこのサイトの Pagefind インデックスを検索します。正規表現はブラウザに読み込んだページインデックスに対してローカルで評価されます。",
  "search.indexFailed": "ページインデックスを読み込めなかったため、このページでは正規表現検索を利用できません。",
  "search.pagefindFailed": "このビルドには Pagefind がないため、プレーンテキストもローカルのページインデックスを検索します。",
  "search.clear": "検索語を消去",
  "search.hint": "/ キーで検索",
  "search.matchesOnPage": "{count} 件一致",
  "search.moreResults": "最初の {count} 件のみ表示しています。検索語を絞ると残りを確認できます。",

  "settings.search": "設定を検索",
  "settings.searchPh": "名前・説明・現在の値で検索",
  "settings.shown": "{total} 件中 {shown} 件の設定",
  "settings.none": "一致する設定はありません。",
  "toc.search": "このページの見出しを検索",
  "toc.searchPh": "このページの見出しを絞り込む",
  "toc.none": "一致する見出しはありません。",
  "toc.shown": "{total} 件中 {shown} 件の見出し",
  "settings.elsewhere": "別のタブにあと {count} 件: {tabs}",
  "settings.clear": "検索語を消去",

  "regex.open": "正規表現ビルダーを開く",
  "regex.title": "正規表現ビルダー",
  "regex.close": "正規表現ビルダーを閉じる",
  "regex.engineNote": "エンジン: ECMAScript RegExp。このブラウザ内でローカルに評価され、入力内容はどこにも送信されません。",
  "regex.pattern": "パターン",
  "regex.patternCap": "{cap} 文字中 {used} 文字",
  "regex.flags": "フラグ",
  "regex.invalid": "無効なパターン",
  "regex.build": "ガイド付き構築",
  "regex.palette": "トークンパレット",
  "regex.sample": "サンプルテキスト",
  "regex.sampleCap": "{cap} 文字中 {used} 文字",
  "regex.sampleSeeded": "この検索が実際に見ている内容から取り込んでいるので、ここで一致すればあちらでも一致します。",
  "regex.matches": "一致",
  "regex.matchCountValue": "{count} 件一致",
  "regex.matchTruncated": "{cap} 件の上限で停止しました — パターンを絞ると残りを確認できます。",
  "regex.noMatches": "サンプルテキストに一致はありません。",
  "regex.groups": "キャプチャグループ",
  "regex.noGroups": "このパターンには名前付きキャプチャグループがありません。",
  "regex.safety": "ローカルで評価され、送信されることはありません。パターンは {pattern} 文字、サンプルは {sample} 文字、一致は {matches} 件で上限を設け、ゼロ幅一致は強制的に前進するため、破滅的なパターンでもページが固まることはありません。",
  "regex.apply": "適用",
  "regex.applyHint": "適用するとパターンが入力欄に入り、正規表現モードに切り替わります。",
  "regex.applyHintPlain": "適用するとパターンが入力欄に入ります。",
  "regex.flagG": "global — 最初の 1 件だけでなくすべての一致を探す",
  "regex.flagI": "大文字小文字を区別しない",
  "regex.flagM": "multiline — ^ と $ が行境界に一致",
  "regex.flagS": "dotall — . が改行にも一致",
  "regex.flagU": "Unicode",
  "regex.flagY": "sticky — lastIndex の位置でのみ一致",
  "regex.groupLiterals": "リテラル",
  "regex.groupClasses": "文字クラス",
  "regex.groupAnchors": "アンカー",
  "regex.groupGroups": "グループ",
  "regex.groupAlternation": "選択",
  "regex.groupQuantifiers": "量指定子",
  "regex.tokLiteral": "リテラル文字列",
  "regex.tokEscapedDot": "エスケープしたドット — リテラルの .",
  "regex.tokBackslash": "リテラルのバックスラッシュ",
  "regex.tokDigit": "任意の数字",
  "regex.tokWord": "任意の単語文字",
  "regex.tokSpace": "任意の空白",
  "regex.tokAny": "任意の 1 文字",
  "regex.tokClass": "文字クラス",
  "regex.tokNegated": "/ 以外の任意の文字",
  "regex.tokUnicodeScript": "Unicode 用字 — u フラグが必要",
  "regex.tokStart": "入力の先頭",
  "regex.tokEnd": "入力の末尾",
  "regex.tokBoundary": "単語境界",
  "regex.tokCapture": "キャプチャグループ",
  "regex.tokNamed": "名前付きキャプチャグループ",
  "regex.tokGroup": "キャプチャしないグループ",
  "regex.tokLookahead": "先読み",
  "regex.tokAlt": "どちらか一方",
  "regex.tokStar": "0 回以上",
  "regex.tokPlus": "1 回以上",
  "regex.tokOpt": "省略可能",
  "regex.tokRange": "1 回から 3 回",
  "regex.tokLazy": "1 回以上、最短一致",
};

const TABLES: Record<StringsLocale, Strings> = { root: EN, ko: KO, "zh-cn": ZH, ru: RU, ja: JA };

/**
 * Substitute `{name}` placeholders.
 *
 * Only the placeholders actually supplied are replaced; an unsupplied one stays
 * literally `{count}` in the output. That is deliberate — a template quietly
 * losing its number reads as a finished sentence and ships, while a visible
 * `{count}` is caught the first time anyone looks at the screen.
 */
export function fmt(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in vars ? String(vars[key]) : whole);
}

export type TFn = (key: string, vars?: Record<string, string | number>) => string;

/**
 * A translator for one locale.
 *
 * Takes a plain `string` key rather than `StringKey` because the guided
 * palette's keys arrive from `shared/m3/regex.ts` typed as the dashboard's own
 * `TKey` union, and narrowing them here would need a cast at every call site.
 * An unknown key returns its own last dotted segment rather than an empty
 * string: a chip labelled `tokNewThing` is ugly and obviously wrong, which is
 * exactly what an untranslated key should look like.
 */
export function translator(locale: StringsLocale): TFn {
  const table = TABLES[locale] ?? EN;
  return (key, vars) => {
    const value = (table as Record<string, string | undefined>)[key]
      ?? (EN as Record<string, string | undefined>)[key];
    return fmt(value ?? key.split(".").pop() ?? key, vars);
  };
}

/** The whole table for a locale, for callers that want direct lookups. */
export function stringsFor(locale: StringsLocale): Strings {
  return TABLES[locale] ?? EN;
}
