/**
 * A minimal QR encoder — byte mode, error correction level M.
 *
 * Written rather than depended on. The dashboard needs exactly one thing from
 * QR: turn a short `http://…/#/mobile` URL into a matrix so a phone can open it
 * without anyone retyping a LAN address and a 40-character key. A library for
 * that is a build-time dependency and a supply-chain surface for ~250 lines of
 * a fully specified algorithm (ISO/IEC 18004).
 *
 * **This is verified against a reference implementation, not eyeballed.**
 * `gui/tests/qr.test.ts` compares the matrix produced here, module for module,
 * against fixtures generated by Python's `qrcode` package. An encoder that is
 * subtly wrong still renders a convincing-looking square that no phone can
 * read, so "it looks like a QR code" is not evidence of anything.
 *
 * Scope is deliberately narrow: byte mode, ECC level M, versions 1–10 (up to
 * 154 bytes at M), automatic version selection, and the mask chosen by the
 * standard's penalty rules. Longer payloads throw rather than silently
 * truncating.
 */

/** Data codeword capacity at ECC level M, indexed by version (1-based). */
const DATA_CODEWORDS_M = [0, 16, 28, 44, 64, 86, 108, 124, 154, 182, 216];
/** EC codewords per block at level M, by version. */
const EC_PER_BLOCK_M = [0, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26];
/** Number of error-correction blocks at level M, by version. */
const BLOCKS_M = [0, 1, 1, 1, 2, 2, 4, 4, 4, 5, 5];

/** Alignment-pattern centre coordinates by version. */
const ALIGNMENT: number[][] = [
  [], [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50],
];

// ---- GF(256) ---------------------------------------------------------------

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d; // QR's primitive polynomial
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

function mul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]];
}

/** Generator polynomial for `degree` error-correction codewords. */
function generator(degree: number): number[] {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array<number>(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= mul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

function ecCodewords(data: number[], count: number): number[] {
  const gen = generator(count);
  const rem = new Array<number>(count).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.shift();
    rem.push(0);
    for (let i = 0; i < count; i++) rem[i] ^= mul(gen[i + 1], factor);
  }
  return rem;
}

// ---- bit stream ------------------------------------------------------------

class Bits {
  readonly bits: number[] = [];
  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }
}

/** The smallest version 1–10 whose level-M capacity holds `byteLength`. */
function pickVersion(byteLength: number): number {
  for (let v = 1; v <= 10; v++) {
    // 4 bits mode + 8 or 16 bits length + payload
    const lengthBits = v < 10 ? 8 : 16;
    if (DATA_CODEWORDS_M[v] * 8 >= 4 + lengthBits + byteLength * 8) return v;
  }
  throw new Error(`payload too long for QR versions 1-10 at ECC level M: ${byteLength} bytes`);
}

// ---- matrix ----------------------------------------------------------------

type Grid = (0 | 1 | null)[][];

function placeFunctionPatterns(grid: Grid, size: number, version: number): void {
  const finder = (row: number, col: number) => {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const rr = row + r;
        const cc = col + c;
        if (rr < 0 || rr >= size || cc < 0 || cc >= size) continue;
        const edge = r === -1 || r === 7 || c === -1 || c === 7;
        const ring = (r === 0 || r === 6) && c >= 0 && c <= 6;
        const side = (c === 0 || c === 6) && r >= 0 && r <= 6;
        const core = r >= 2 && r <= 4 && c >= 2 && c <= 4;
        grid[rr][cc] = edge ? 0 : (ring || side || core) ? 1 : 0;
      }
    }
  };
  finder(0, 0);
  finder(0, size - 7);
  finder(size - 7, 0);

  // Timing patterns.
  for (let i = 8; i < size - 8; i++) {
    const bit = (i % 2 === 0 ? 1 : 0) as 0 | 1;
    grid[6][i] = bit;
    grid[i][6] = bit;
  }

  // Alignment patterns, skipping the three finder corners.
  const centres = ALIGNMENT[version];
  for (const r of centres) {
    for (const c of centres) {
      const nearFinder = (r <= 8 && c <= 8) || (r <= 8 && c >= size - 9) || (r >= size - 9 && c <= 8);
      if (nearFinder) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const ring = Math.max(Math.abs(dr), Math.abs(dc));
          grid[r + dr][c + dc] = (ring === 1 ? 0 : 1) as 0 | 1;
        }
      }
    }
  }

  // Dark module.
  grid[size - 8][8] = 1;
}

/**
 * Reserve exactly the cells `applyFormat` writes, so data placement skips those
 * and only those.
 *
 * The horizontal run of the second copy covers columns `size-7 … size-1` —七
 * cells for bits 8‑14. Reserving `size-8` as well (the intuitive symmetric
 * range) steals one ordinary data module: placement skips it, nothing ever
 * writes it, and it stays null. One missing module is enough to make the whole
 * symbol undecodable.
 */
function reserveFormat(grid: Grid, size: number): void {
  for (let i = 0; i <= 8; i++) {
    if (grid[8][i] === null) grid[8][i] = 0;
    if (grid[i][8] === null) grid[i][8] = 0;
  }
  for (let i = 0; i < 8; i++) {
    if (grid[8][size - 1 - i] === null) grid[8][size - 1 - i] = 0;
    if (grid[size - 1 - i][8] === null) grid[size - 1 - i][8] = 0;
  }
}

const MASKS: ((r: number, c: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  r => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

/** ISO/IEC 18004 penalty score, used to choose the mask. */
function penalty(m: number[][], size: number): number {
  let score = 0;

  // Rule 1: runs of five or more same-colour modules.
  for (let i = 0; i < size; i++) {
    for (const line of [m[i], m.map(row => row[i])]) {
      let run = 1;
      for (let j = 1; j < size; j++) {
        if (line[j] === line[j - 1]) { run++; } else { if (run >= 5) score += run - 2; run = 1; }
      }
      if (run >= 5) score += run - 2;
    }
  }

  // Rule 2: 2x2 blocks of one colour.
  for (let r = 0; r < size - 1; r++) {
    for (let c = 0; c < size - 1; c++) {
      const v = m[r][c];
      if (v === m[r][c + 1] && v === m[r + 1][c] && v === m[r + 1][c + 1]) score += 3;
    }
  }

  // Rule 3: the finder-like 1:1:3:1:1 pattern with four light modules.
  const A = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const B = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
  const matches = (line: number[], at: number, pat: number[]) =>
    pat.every((v, k) => line[at + k] === v);
  for (let i = 0; i < size; i++) {
    for (const line of [m[i], m.map(row => row[i])]) {
      for (let j = 0; j + 11 <= size; j++) {
        if (matches(line, j, A) || matches(line, j, B)) score += 40;
      }
    }
  }

  // Rule 4: deviation from a 50% dark ratio.
  let dark = 0;
  for (const row of m) for (const v of row) dark += v;
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

const FORMAT_GENERATOR = 0b10100110111;
const FORMAT_MASK = 0b101010000010010;

/** 15-bit format information for ECC level M and a mask index. */
function formatBits(mask: number): number {
  const data = (0b00 << 3) | mask; // 00 = level M
  let rem = data << 10;
  for (let i = 4; i >= 0; i--) {
    if (rem & (1 << (i + 10))) rem ^= FORMAT_GENERATOR << i;
  }
  return ((data << 10) | rem) ^ FORMAT_MASK;
}

export interface QrMatrix {
  size: number;
  /** Row-major, 1 = dark. */
  modules: number[][];
  version: number;
}

/**
 * Encode `text` as a QR matrix.
 *
 * Throws for a payload that does not fit versions 1–10 at level M, rather than
 * truncating — a truncated QR scans cleanly to the wrong URL, which is the one
 * outcome worse than no QR at all.
 */
export function encodeQr(text: string): QrMatrix {
  const data = [...new TextEncoder().encode(text)];
  const version = pickVersion(data.length);
  const size = 17 + version * 4;
  const totalData = DATA_CODEWORDS_M[version];

  // Mode indicator, length, payload, terminator, padding.
  const bits = new Bits();
  bits.push(0b0100, 4);
  bits.push(data.length, version < 10 ? 8 : 16);
  for (const byte of data) bits.push(byte, 8);
  const capacity = totalData * 8;
  bits.push(0, Math.min(4, capacity - bits.bits.length));
  while (bits.bits.length % 8 !== 0) bits.bits.push(0);
  const codewords: number[] = [];
  for (let i = 0; i < bits.bits.length; i += 8) {
    codewords.push(bits.bits.slice(i, i + 8).reduce((acc, b) => (acc << 1) | b, 0));
  }
  const PAD = [0xec, 0x11];
  for (let i = 0; codewords.length < totalData; i++) codewords.push(PAD[i % 2]);

  // Split into blocks, interleave data then EC.
  const blockCount = BLOCKS_M[version];
  const ecCount = EC_PER_BLOCK_M[version];
  const shortLen = Math.floor(totalData / blockCount);
  const longCount = totalData % blockCount;
  const dataBlocks: number[][] = [];
  const ecBlocks: number[][] = [];
  let offset = 0;
  for (let b = 0; b < blockCount; b++) {
    const len = shortLen + (b >= blockCount - longCount ? 1 : 0);
    const block = codewords.slice(offset, offset + len);
    offset += len;
    dataBlocks.push(block);
    ecBlocks.push(ecCodewords(block, ecCount));
  }
  const interleaved: number[] = [];
  for (let i = 0; i < shortLen + 1; i++) {
    for (const block of dataBlocks) if (i < block.length) interleaved.push(block[i]);
  }
  for (let i = 0; i < ecCount; i++) {
    for (const block of ecBlocks) interleaved.push(block[i]);
  }

  // Function patterns first, so data placement can skip them.
  const grid: Grid = Array.from({ length: size }, () => new Array(size).fill(null));
  placeFunctionPatterns(grid, size, version);
  const reserved: Grid = grid.map(row => [...row]);
  reserveFormat(reserved, size);

  // Data placement: two-module columns, upward then downward, skipping column 6.
  const stream: number[] = [];
  for (const byte of interleaved) for (let i = 7; i >= 0; i--) stream.push((byte >>> i) & 1);
  let idx = 0;
  let upward = true;
  for (let right = size - 1; right > 0; right -= 2) {
    if (right === 6) right = 5;
    for (let step = 0; step < size; step++) {
      const row = upward ? size - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (reserved[row][col] !== null) continue;
        grid[row][col] = ((idx < stream.length ? stream[idx] : 0) as 0 | 1);
        idx++;
      }
    }
    upward = !upward;
  }

  // Choose the mask by penalty, then write its format information.
  let best: number[][] | null = null;
  let bestMask = 0;
  let bestScore = Infinity;
  for (let mask = 0; mask < 8; mask++) {
    const candidate = grid.map((row, r) => row.map((v, c) =>
      reserved[r][c] !== null ? (v as number) : (v as number) ^ (MASKS[mask](r, c) ? 1 : 0)));
    applyFormat(candidate, size, mask);
    const score = penalty(candidate, size);
    if (score < bestScore) { bestScore = score; best = candidate; bestMask = mask; }
  }
  void bestMask;

  return { size, modules: best!, version };
}

function applyFormat(m: number[][], size: number, mask: number): void {
  const fmt = formatBits(mask);
  for (let i = 0; i < 15; i++) {
    // MSB-first: cell index 0 carries bit 14. Indexing from the LSB instead
    // swaps bit i with bit 14-i, which is invisible wherever the format word
    // happens to be symmetric and silently corrupts it everywhere else — the
    // failure only shows up as "some phones will not scan this".
    const bit = (fmt >>> (14 - i)) & 1;
    // Copy 1, around the top-left finder.
    if (i < 6) m[8][i] = bit;
    else if (i === 6) m[8][7] = bit;
    else if (i === 7) m[8][8] = bit;
    else if (i === 8) m[7][8] = bit;
    else m[14 - i][8] = bit;
    // Copy 2, split 7 vertical + 8 horizontal between the other two finders.
    // The boundary is 7, not 8: column `size-8` carries a format bit, and
    // treating it as the start of the run rather than its end drops one bit and
    // leaves that module unwritten.
    if (i < 7) m[size - 1 - i][8] = bit;
    else m[8][size - 15 + i] = bit;
  }
  m[size - 8][8] = 1; // dark module, never masked
}

/**
 * The matrix as a standalone SVG path string, plus its viewBox size.
 *
 * A quiet zone of 4 modules is included because scanners need it; a QR rendered
 * flush to its container edge frequently will not read.
 */
export function qrSvgPath(matrix: QrMatrix, quiet = 4): { path: string; size: number } {
  const parts: string[] = [];
  for (let r = 0; r < matrix.size; r++) {
    for (let c = 0; c < matrix.size; c++) {
      if (matrix.modules[r][c]) parts.push(`M${c + quiet} ${r + quiet}h1v1h-1z`);
    }
  }
  return { path: parts.join(""), size: matrix.size + quiet * 2 };
}
