/**
 * Regenerate `gui/src/docs/generated-articles.ts` — the in-app documentation
 * browser's bundled corpus — from the documentation site's plain-Markdown
 * articles.
 *
 *   bun run scripts/gen-docs-articles.ts
 *
 * ## Why a committed generated file, not a Vite virtual module
 *
 * The obvious build-time mechanism is a Vite plugin exposing a
 * `virtual:opencodex-docs` module that reads the docs-site tree while
 * bundling. It was tried first and abandoned: `gui/tests/*.test.ts` files run
 * under `bun test`, never through Vite, and Bun has no idea what to do with a
 * bare `virtual:` specifier — every page in this app that has a test imports
 * the real page component directly (see `tests/changelog-export.test.tsx`
 * importing `../src/pages/Changelog`), and a docs page that could only be
 * exercised through an actual `vite build` would be the one page in the app
 * nothing local could verify.
 *
 * A committed, generated module sidesteps that completely: it is an ordinary
 * TypeScript file, importable exactly like `icons.tsx` (also GENERATED, also
 * committed, same reasoning) from both `bun test` and `vite build` without
 * either one needing to know how the other produces it. The content becomes
 * static JS the moment this file is committed — no network fetch, nothing
 * that can fail the moment a shipped build goes offline.
 *
 * This is wired into `gui/package.json`'s `build` script, so a real release
 * build always regenerates from whatever is on disk at that moment rather
 * than trusting a possibly-stale commit. `gui/tests/docs-articles-complete.test.ts`
 * is the other half: it independently re-walks the same source directory and
 * fails `bun test` — the gate this repository actually enforces locally, see
 * `docs/FEATURE-INVENTORY.md`'s notes on CI running no tests — the moment the
 * committed file stops matching what is really on disk, e.g. because someone
 * added a new guide and forgot to re-run this script.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildArticleBundle, DOCS_SITE_CONTENT_ROOT } from "./docs-article-source.ts";
import { DOC_CATEGORY_ORDER, type DocCategory } from "../gui/src/docs/types.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = join(ROOT, "gui", "src", "docs", "generated-articles.ts");

const articles = buildArticleBundle(DOCS_SITE_CONTENT_ROOT);

// A hard sanity floor, independent of `buildArticleBundle`'s own logic: every
// real category must have contributed at least one article. This is what
// catches "the whole `guides/` directory silently stopped being discovered" —
// a bug that would otherwise write a perfectly well-formed, perfectly wrong
// generated file with nobody the wiser until a user went looking for a page
// that used to be there.
const counts = new Map<DocCategory, number>();
for (const a of articles) counts.set(a.category, (counts.get(a.category) ?? 0) + 1);
const missingCategories = DOC_CATEGORY_ORDER.filter(c => c !== "general" && (counts.get(c) ?? 0) === 0);
if (missingCategories.length > 0) {
  console.error(`gen-docs-articles: found zero articles for ${missingCategories.join(", ")} — refusing to write a bundle that is missing a whole category.`);
  process.exit(1);
}
if (articles.length < 20) {
  console.error(`gen-docs-articles: only found ${articles.length} article(s) under ${DOCS_SITE_CONTENT_ROOT} — expected at least 20. Refusing to write a suspiciously small bundle.`);
  process.exit(1);
}

const ids = new Set<string>();
for (const a of articles) {
  if (ids.has(a.id)) {
    console.error(`gen-docs-articles: duplicate article id "${a.id}" — two files produced the same category/slug.`);
    process.exit(1);
  }
  ids.add(a.id);
}

const lines = articles.map(a => `  ${JSON.stringify(a)},`);

const out = `/* GENERATED by scripts/gen-docs-articles.ts — do not edit by hand.
 *
 * The in-app documentation browser's bundled corpus, taken verbatim from the
 * plain-Markdown articles under \`docs-site/src/content/docs/\` (excluding
 * locale mirrors and \`.mdx\` component pages — see that script's header for
 * why). Re-run it to pick up a new or edited article:
 *
 *   bun run scripts/gen-docs-articles.ts
 *
 * \`gui/tests/docs-articles-complete.test.ts\` fails \`bun test\` if this file
 * stops matching what is actually on disk.
 */
import type { DocArticle } from "./types";

export const DOCS_ARTICLES: DocArticle[] = [
${lines.join("\n")}
];
`;

writeFileSync(OUT_FILE, out, "utf8");
console.log(`Wrote ${OUT_FILE} — ${articles.length} articles across ${counts.size} categories.`);
for (const c of DOC_CATEGORY_ORDER) {
  if (counts.get(c)) console.log(`  ${c}: ${counts.get(c)}`);
}
